### ISSUE TITLE
SystemJS URL polyfill constructor accepts URL objects

### ISSUE THREAD

**Issue by mightyguava** [systemjs/systemjs#1036]
I'm running `jsdom` on `node` to load a web page that uses `SystemJS`. `System.import` is failing with the error below:

```
I20160115 21:56:48 exportApp.js:41| Page and resources loaded
I20160115 21:56:48 exportApp.js:42| Initializing SystemJS
E20160115 21:56:48 exportApp.js:47| TypeError: url.replace is not a function
    at trimControlChars (/Users/yunchi/development/src/js/node_modules/whatwg-url-compat/lib/url.js:455:14)
    at new URLStateMachine (/Users/yunchi/development/src/js/node_modules/whatwg-url-compat/lib/url.js:480:18)
    at URL.init (/Users/yunchi/development/src/js/node_modules/whatwg-url-compat/lib/url.js:1324:18)
    at new URL (/Users/yunchi/development/src/js/node_modules/whatwg-url-compat/lib/url.js:1344:10)
    at SystemJSLoader.<anonymous> (http://localhost:5000/static/systemjs_apps/jspm_packages/system.js:1885:14)
    at SystemJSLoader.<anonymous> (http://localhost:5000/static/systemjs_apps/jspm_packages/system.js:2186:34)
    at SystemJSLoader.<anonymous> (http://localhost:5000/static/systemjs_apps/jspm_packages/system.js:3572:24)
    at SystemJSLoader.normalizePlugin (http://localhost:5000/static/systemjs_apps/jspm_packages/system.js:4070:24)
    at SystemJSLoader.<anonymous> (http://localhost:5000/static/systemjs_apps/jspm_packages/system.js:4077:30)
    at http://localhost:5000/static/systemjs_apps/jspm_packages/system.js:4342:26
```

Specifically, it fails at https://github.com/systemjs/systemjs/blob/master/lib/core.js#L156. I believe it's because the current verison of `jsdom` includes a more strict version of whatwg URL https://github.com/jsdom/whatwg-url.

`SystemJS` passes in the `URL` object for the second argument, whereas the whatwg URL spec mandates that both params must be strings https://url.spec.whatwg.org/#api. The SystemJS polyfill seems to actually accept both and prefer URL. https://github.com/systemjs/systemjs/blob/master/dist/system-polyfills.src.js#L25

I _think_ the fix just requires that wherever a URL object is used for the second argument, pass in its `href` attribute instead.

**Comment by onlywei** [comment]
+1

**Comment by maaravi** [comment]
+1!

**Comment by marcusmolchany** [comment]
+1

**Comment by guybedford** [comment]
The URL constructor in browser implementations does work with the URL object as a second argument. This is nice to have for performance as well. We should retain that but then allow cases where URL not as an object in the second argument can be supported too. This can likely be implemented through an internal wrapper function on the URL calls.

**Comment by onlywei** [comment]
@guybedford @mightyguava I've done some more research on this topic and I think I'm still confused by the spec. I've opened an issue with them here: https://github.com/whatwg/url/issues/80

Then I looked at [MDN](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) and their examples clearly allow a `URL` object to be passed in as the second argument.

Right now I'm thinking that https://github.com/jsdom/whatwg-url is the wrong one here...

**Comment by mightyguava** [comment]
@guybedford @onlywei thanks for looking into this! I'm gonna close this issue then. The response from whatwg/url spec is still very confusing as to what the "right" behavior is...
