### ISSUE TITLE
Can't run on Android 4.4

### ISSUE THREAD

**Issue by fr3dm4n** [systemjs/systemjs#1077]
I have a dummy app, which is running perfectly at Chrome on win10 and per Cordova on Android 5.1. But with Cordova on Android 4.4 I get following error:
```
undefined is not a function
	Error loading file:///android_asset/www/app/boot.js
TypeError: undefined is not a function
    at <anonymous>:1:12022
    at <anonymous>:1:12172
    at linkDynamicModule (file:///android_asset/www/bundles/system.src.js:3142:32)
    at getModule (file:///android_asset/www/bundles/system.src.js:3110:9)
    at file:///android_asset/www/bundles/system.src.js:3146:16
    at <anonymous>:8:26725
    at linkDynamicModule (file:///android_asset/www/bundles/system.src.js:3142:32)
    at getModule (file:///android_asset/www/bundles/system.src.js:3110:9)
    at file:///android_asset/www/bundles/system.src.js:3146:16
    at <anonymous>:10:14666
```

my boot.js comes from this TypeScript:
```typescript
import {JokeService} from "./services/JokeService";
import {AppComponent} from "./components/app/app.component"
import {bootstrap} from "angular2/platform/browser"
import {ROUTER_PROVIDERS,APP_BASE_HREF,HashLocationStrategy,LocationStrategy,RouterLink} from "angular2/router"
import {HTTP_PROVIDERS} from "angular2/http";
import {UrlResolver} from "angular2/compiler";
import {MobileUrlResolver} from "./services/MobileUrlResolver";
import {provide,enableProdMode} from "angular2/core";
import {TelemetrieService} from "./services/TelemetrieService";
import {TitleService} from "./services/TitleService";
import {FormBuilder,FORM_DIRECTIVES} from "angular2/common";


var isCordovaApp = document.URL.indexOf( 'http://' ) === -1 && document.URL.indexOf( 'https://' ) === -1;

var bootstrapOptions=[
    ROUTER_PROVIDERS,
    HTTP_PROVIDERS,
    FormBuilder,
    JokeService,
    RouterLink,
    TitleService,
    TelemetrieService,
    provide(APP_BASE_HREF, {useValue : '/'}),
    provide(UrlResolver,{useClass:MobileUrlResolver})
];

if(isCordovaApp){
    bootstrapOptions.push(provide(LocationStrategy, {useClass:HashLocationStrategy}));
}
bootstrap(AppComponent, bootstrapOptions);
```

My tsconfig.json:
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  },
  "files": [
    "node_modules/angular2"
  ],
  "exclude": [
    "node_modules",
    "www",
    "platforms"
  ]
}
```

Did I miss something?

**Comment by fr3dm4n** [comment]
Nevermind... after using Crosswalks everything is fine. Sry for disturbance ;)
