### ISSUE TITLE
Dust.js amd not working with systemjs

### ISSUE THREAD

**Issue by gajewsk2** [systemjs/systemjs#1096]
Trying to load dust.js via the amd module syntax. Works just fine if the meta is set to global and templates are built with the amd setting. 
According to the [dust amd docs](https://github.com/linkedin/dustjs/wiki/Loading-Dust-via-AMD-(require.js)) you need to set `define.amd.dust = true;`
```javascripts
  window.define = System.amdDefine;
  window.require = window.requirejs = System.amdRequire;
  define.amd.dust = true;
```

But when this loads I am getting this. Debugging has shown me that define.amd is getting erased for some reason before the dust-core.js gets loaded, and then I get this error because dust doesn't know it should be in amd mode.
```
Uncaught (in promise) Error: AMD module http://localhost:8000/static/jspm_packages/github/linkedin/dustjs@2.7.2/dist/dust-core.js did not define
	Error loading http://localhost:8000/static/jspm_packages/github/linkedin/dustjs@2.7.2/dist/dust-core.js as "github:linkedin/dustjs@2.7.2/dist/dust-core.js" from http://localhost:8000/static/jspm_packages/github/linkedin/dustjs@2.7.2.js
    at l.<anonymous> (http://localhost:8000/static/jspm_packages/system.js:5:17431)
    at l.instantiate (http://localhost:8000/static/jspm_packages/system.js:5:20405)
    at http://localhost:8000/static/jspm_packages/system.js:4:6337
```

**Comment by guybedford** [comment]
@gajewsk2 that's really odd if `define.amd` is not present. Can you perhaps share the value of `define.toString()` that gives that, it doesn't sound like that is the SystemJS define actually then. Perhaps try using the latest version of SystemJS which avoids a timing issue that might cause something like that.

**Comment by gajewsk2** [comment]
Systemjs v0.19.18 , jspm: v0.16.27
``` javascript
function define(name, deps, factory) {
      if (typeof name != 'string') {
        factory = deps;
        deps = name;
        name = null;
      }
      if (!(deps instanceof Array)) {
        factory = deps;
        deps = ['require', 'exports', 'module'].splice(0, factory.length);
      }

      if (typeof factory != 'function')
        factory = (function(factory) {
          return function() { return factory; }
        })(factory);

      // in IE8, a trailing comma becomes a trailing undefined entry
      if (deps[deps.length - 1] === undefined)
        deps.pop();

      // remove system dependencies
      var requireIndex, exportsIndex, moduleIndex;
      
      if ((requireIndex = indexOf.call(deps, 'require')) != -1) {
        
        deps.splice(requireIndex, 1);

        // only trace cjs requires for non-named
        // named defines assume the trace has already been done
        if (!name)
          deps = deps.concat(getCJSDeps(factory.toString(), requireIndex));
      }

      if ((exportsIndex = indexOf.call(deps, 'exports')) != -1)
        deps.splice(exportsIndex, 1);
      
      if ((moduleIndex = indexOf.call(deps, 'module')) != -1)
        deps.splice(moduleIndex, 1);

      function execute(req, exports, module) {
        var depValues = [];
        for (var i = 0; i < deps.length; i++)
          depValues.push(req(deps[i]));

        module.uri = module.id;

        module.config = function() {};

        // add back in system dependencies
        if (moduleIndex != -1)
          depValues.splice(moduleIndex, 0, module);
        
        if (exportsIndex != -1)
          depValues.splice(exportsIndex, 0, exports);
        
        if (requireIndex != -1) {
          function contextualRequire(names, callback, errback) {
            if (typeof names == 'string' && typeof callback != 'function')
              return req(names);
            return require.call(loader, names, callback, errback, module.id);
          }
          contextualRequire.toUrl = function(name) {
            // normalize without defaultJSExtensions
            var defaultJSExtension = loader.defaultJSExtensions && name.substr(name.length - 3, 3) != '.js';
            var url = loader.decanonicalize(name, module.id);
            if (defaultJSExtension && url.substr(url.length - 3, 3) == '.js')
              url = url.substr(0, url.length - 3);
            return url;
          };
          depValues.splice(requireIndex, 0, contextualRequire);
        }

        // set global require to AMD require
        var curRequire = __global.require;
        __global.require = require;

        var output = factory.apply(exportsIndex == -1 ? __global : exports, depValues);

        __global.require = curRequire;

        if (typeof output == 'undefined' && module)
          output = module.exports;

        if (typeof output != 'undefined')
          return output;
      }

      var entry = createEntry();
      entry.name = name && (loader.decanonicalize || loader.normalize).call(loader, name);
      entry.deps = deps;
      entry.execute = execute;

      loader.pushRegister_({
        amd: true,
        entry: entry
      });
    }
```

**Comment by gajewsk2** [comment]
Not sure what changed, but i do have `define.amd.dust = true` set properly now inside of dust-core.js. 
It's still giving me this though:
```
Uncaught (in promise) Uncaught TypeError: Multiple defines for anonymous module http://localhost:8000/static/jspm_packages/github/linkedin/dustjs@2.7.2/dist/dust-core.js
	Evaluating http://localhost:8000/static/jspm_packages/github/linkedin/dustjs@2.7.2/dist/dust-core.js
	Error loading http://localhost:8000/static/jspm_packages/github/linkedin/dustjs@2.7.2/dist/dust-core.js as "github:linkedin/dustjs@2.7.2/dist/dust-core.js" from http://localhost:8000/static/jspm_packages/github/linkedin/dustjs@2.7.2.js
```

**Comment by guybedford** [comment]
@gajewsk2 if you look at the source of https://github.com/linkedin/dustjs/blob/v2.7.2/dist/dust-core.js, it contains two `define(` statements, one named and one anonymous. So it is actually invalid AMD. Try treating it as a global or CommonJS file rather.

**Comment by guybedford** [comment]
This has actually been fixed in the latest release.
