### ISSUE TITLE
When meta "exports" is an array, get TypeError: p.split is not a function

### ISSUE THREAD

**Issue by kwesterfeld** [systemjs/systemjs#1133]
(Moving from jspm, https://github.com/jspm/jspm-cli/issues/1579, because this looks like systemjs issue, not jspm)

I am migrating my app to 0.17 beta, and have a bunch of overrides and could not load my application due to the following exception:

```
TypeError: p.split is not a function
    at readMemberExpression (https://localhost:8183/smc/jspm_packages/system.src.js:1450:18)
    at loader.set.loader.newModule.prepareGlobal (https://localhost:8183/smc/jspm_packages/system.src.js:3624:27)
    at entry.execute (https://localhost:8183/smc/jspm_packages/system.src.js:3534:16)
    at linkDynamicModule (https://localhost:8183/smc/jspm_packages/system.src.js:3132:32)
    at link (https://localhost:8183/smc/jspm_packages/system.src.js:2975:11)
    at Object.Promise.all.then.normalizedDeps.execute (https://localhost:8183/smc/jspm_packages/system.src.js:3312:13)
    at doDynamicExecute (https://localhost:8183/smc/jspm_packages/system.src.js:708:25)
    at link (https://localhost:8183/smc/jspm_packages/system.src.js:910:20)
    at doLink (https://localhost:8183/smc/jspm_packages/system.src.js:562:7)
    at updateLinkSetOnLoad (https://localhost:8183/smc/jspm_packages/system.src.js:610:18)
```

It turns out that my overrides sometimes declared exports as an array, which the new version does not support.

For example, the conversion of my 0.16 override left this in place:

```
      "npm:bootbox@4.4.0": {
        "main": "bootbox",
        "format": "global",
        "files": [
          "bootbox.js",
          "bower.json",
          "package.json",
          "LICENSE*",
          "README*"
        ],
        "meta": {
          "bootbox.js": {
            "exports": [
              "bootbox"
            ],
            "format": "global"
          }
        }
      },
```

changing exports to a single entry works, but seems like it should have been converted, handled or warned.

**Comment by guybedford** [comment]
This is correct as currently designed, exports as an array is not supported pending https://github.com/systemjs/systemjs/issues/443.

**Comment by kwesterfeld** [comment]
Guy....don't get me wrong if this isn't supported, but the behavior changed w.r.t. 0.16 release.  At least, the 0.16 release would not throw this error.  Can you add a warning for this case to indicate the array form is not supported until it is?

**Comment by guybedford** [comment]
@kwesterfeld you are completely right this was a break, although it is true that jspm 0.17 is a breaking upgrade as well. Hopefully there will be time to address SystemJS issue #443 to resolve this.
