### ISSUE TITLE
Unhandled rejection TypeError: Incorrect configuration order. The baseURL must be configured with the first SystemJS.config call

### ISSUE THREAD

**Issue by darrenshrwd** [systemjs/systemjs#1195]
I think I did both an npm and jspm update and suddenly I get the error below, I did not get it before, if I run with my old version of gulpfile I still get the error and if I revert to old versions of package.json or config.js  I still get some kind of error.  I've attached relevant files.

[The-files.zip](https://github.com/systemjs/systemjs/files/201184/The-files.zip)

```e
Unhandled rejection TypeError: Incorrect configuration order. The baseURL must be configured with the first SystemJS.config call.
    at SystemJSNodeLoader.SystemJSLoader.config (C:\MyProjectPath\node_modules\jspm\node_modules\systemjs\dist\system.src.js:1853:13)
    at SystemJSNodeLoader.loader.config (C:\MyProjectPath\node_modules\jspm\node_modules\systemjs-builder\lib\builder.js:155:18)
    at Builder.config (C:\MyProjectPath\node_modules\jspm\node_modules\systemjs-builder\lib\builder.js:318:15)
    at SystemJSNodeLoader.configLoader.config (C:\MyProjectPath\node_modules\jspm\node_modules\systemjs-builder\lib\builder.js:281:10)
    at evalmachine.<anonymous>:1:8
    at Builder.executeConfigFile (C:\MyProjectPath\node_modules\jspm\node_modules\systemjs-builder\lib\builder.js:297:17)
    at tryCatcher (C:\MyProjectPath\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\MyProjectPath\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\release\promise.js:503:31)
    at Promise._settlePromise (C:\MyProjectPath\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\release\promise.js:560:18)
    at Promise._settlePromise0 (C:\MyProjectPath\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\release\promise.js:605:10)
    at Promise._settlePromises (C:\MyProjectPath\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\release\promise.js:684:18)
    at Promise._fulfill (C:\MyProjectPath\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\release\promise.js:629:18)
    at C:\MyProjectPath\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\release\nodeback.js:42:21
    at fs.js:271:14
    at C:\MyProjectPath\node_modules\jspm\node_modules\jspm-github\node_modules\tar\node_modules\fstream\node_modules\graceful-fs\graceful-fs.js:43:10
    at C:\MyProjectPath\node_modules\jspm\node_modules\jspm-npm\node_modules\tar\node_modules\fstream\node_modules\graceful-fs\graceful-fs.js:43:10
```

**Comment by darrenshrwd** [comment]
By getting previous version I have found the issue is with the config.js will post when narrowed down further

**Comment by darrenshrwd** [comment]
My code is ES5 (apart from the import statements) and I can set **transpiler: false** and it works.

However if I use either typescript or babel transpiler then I get the error (title of this issue).

With typescript it leaves behind these in config.js when uninstalled: 

    "github:jspm/nodelibs-os@0.1.0": {
```
      "os-browserify": "npm:os-browserify@0.1.2"
    },
    "npm:os-browserify@0.1.2": {
      "os": "github:jspm/nodelibs-os@0.1.0"
    },
    "npm:typescript@1.8.9": {
      "os": "github:jspm/nodelibs-os@0.1.0"
    }
```
If I remove them I can get the bundler to 'work' by placing an empty os.js file in my project directory.

**Comment by guybedford** [comment]
In jspm 0.17, the `jspm.browser.js` config file must be loaded after the `jspm.config.js` config file.

It's advisable to use `require('jspm').Builder` instead of `require('systemjs-builder')` which will avoid this issue entirely.

**Comment by darrenshrwd** [comment]
I had already switched to `require('jspm').Builder` but I was still doing `builder.loadConfig` which I now gather is not needed.

_I've just pieced together understanding from a million different blog posts, the wiki links don't seem to work...I'm not complaining...thanks for your awesome work, MS and Google should give you a resource for some updated docs as MS has deprecated their bundling, etc._

**Comment by tom10271** [comment]
I got the same error message while `jspm -v` returns `0.16.31`, what should I do?

I got this error after I update jspm packages

**Comment by tomahim** [comment]
+1

**Comment by zeeshanjan82** [comment]
@guybedford where do we need to add : require('jspm').Builder instead of require('systemjs-builder')
