### ISSUE TITLE
Loader version 0.19.26 very slow IE 11 but not on Edge 

### ISSUE THREAD

**Issue by leon-andria** [systemjs/systemjs#1220]
Before updating the loader version, we are using version 0.19.9.
After the update to 0.19.26, loading on IE11 becomes very slow, like 1 minute and more to load our application.
And moving to jspm dl-loader traceur or babel, we got back to 0.19.9 and the issue is gone.
So, we suspect that there is an issue about Promise on this release.
Below is the warnings we got from IE Console debugger:
Warning: a promise was created in a handler but was not returned from it
    (No stack trace)
From previous event:
   at ready (eval code:32:5)
   at run (eval code:116:5)
   at Anonymous function (eval code:143:3)
   at s (http://localhost:9500/jspm_packages/system.js:5:17746)
   at u (http://localhost:9500/jspm_packages/system.js:5:5125)
   at u (http://localhost:9500/jspm_packages/system.js:5:5103)
   at r (http://localhost:9500/jspm_packages/system.js:5:3694)
   at execute (http://localhost:9500/jspm_packages/system.js:5:8758)
   at y (http://localhost:9500/jspm_packages/system.js:4:12950)
   at w (http://localhost:9500/jspm_packages/system.js:4:13335)
   at p (http://localhost:9500/jspm_packages/system.js:4:11215)
From previous event:
   at d (http://localhost:9500/jspm_packages/system.js:4:8774)
   at u (http://localhost:9500/jspm_packages/system.js:4:8618)
   at l (http://localhost:9500/jspm_packages/system.js:4:8496)
   at Anonymous function (http://localhost:9500/jspm_packages/system.js:4:10535)
From

and a second warning after that:
Warning: a promise was created in a handler but was not returned from it
    (No stack trace)
From previous event:
   at L (http://localhost:9500/jspm_packages/system.js:4:6505)
   at Anonymous function (http://localhost:9500/jspm_packages/system.js:5:23374)
   at DefaultLoader.prototype.normalize (eval code:235:7)
   at Anonymous function (eval code:365:9)
   at next (eval code:250:9)
   at runTasks (eval code:256:5)
   at apply (eval code:516:7)
   at start (eval code:145:7)
   at configure (eval code:45:9)
   at Anonymous function (eval code:104:9)
From previous event:
   at config (eval code:103:7)
   at handleApp (eval code:95:5)
   at Anonymous function (eval code:123:13)
From previous event:
   at Anonymous function (eval code:121:9)
From previous event:
   at Anonymous function (eval code:120:7)
From previous event:
   at run (eval code:116:5)
   at Anonymous function (eval code:143:3)
   at s (http://localhost:9500/jspm_packages/system.js:5:17746)
   at u (http://localhost:9500/jspm_packages/system.j

thanks for your support,

Léon

**Comment by guybedford** [comment]
We added a note at https://github.com/systemjs/systemjs#promise-polyfill to the Readme recently about using Bluebird for promises in IE. Let me know if that helps here?

**Comment by devmondo** [comment]
just to add a note so it may help anyone in the future.
after a lot of tests, we have noticed that IE 11 is freezing with `bluebird`, maybe it is us only or just a general problem. the solution was to include the minified version of `bluebird` instead.

**Comment by leon-andria** [comment]
Thks guy for your support, we fix the issue as @devmondo said
