### ISSUE TITLE
Karma failed to detect soucemaps since systemjs@0.19.19

### ISSUE THREAD

**Issue by unlight** [systemjs/systemjs#1260]
I'm not sure who is responsible for this issue, but found it empirically.

systemjs@0.19.18
![](https://i.gyazo.com/478b227b5c2b2d1b373f444c8923f132.png)

systemjs@0.19.19 - 0.19.27
![](https://i.gyazo.com/87a1deddd2a600af6072665e077759a1.png)

No link to source.

**Comment by guybedford** [comment]
What transpiler workflow are you using in this project?

**Comment by unlight** [comment]
gulp-typescript with Typescript 1.8.10 under the hood.
[tsconfig.json](https://github.com/unlight/angular2-blank-project/blob/3e37f8d38892a2fc386a1d57a232544cd11c23c6/tsconfig.json)
Sourcemap is generated by gulp-sourcemaps. Here is the [sample code](https://github.com/ivogabe/gulp-typescript#source-maps)

**Comment by unlight** [comment]
Created same issue for [karma-runner/karma#2122](https://github.com/karma-runner/karma/issues/2122)

**Comment by guybedford** [comment]
I'm not sure the code in the example you've provided is running through SystemJS though at all here? Are you absolutely sure that just changing the SystemJS version is enough to trigger this?

**Comment by unlight** [comment]
Steps to reproduce:
```
npm install typings -g
npm install gulpjs/gulp-cli#4.0 -g

git clone https://github.com/unlight/angular2-blank-project.git
cd angular2-blank-project
git checkout -f c3b7f7be782cfc3f561134de3564190bcef326b6
npm i
goto src\app\components\app\app.spec.ts change xit -> fit
npm ls systemjs // make sure that we have systemjs@0.19.18
gulp test // outputs app.spec.js:13:49 <- src/app/components/app/app.spec.ts:8:27
npm i systemjs@0.19.19 // or any higher version
npm ls systemjs // make sure that we have systemjs@0.19.19+
gulp test // outputs Expected false to be true... karma.main.js:58:20
```

**Comment by guybedford** [comment]
That gives me the following on gulp test:

```
Guys-MacBook-Air:angular2-blank-project guybedford$ gulp test
[11:58:11] Using gulpfile ~/Projects/test/angular2-blank-project/gulpfile.js
[11:58:11] Starting 'test'...
[11:58:11] Starting 'build'...
[11:58:11] Starting 'clean'...
[11:58:11] Finished 'clean' after 9.14 ms
[11:58:11] Starting '<parallel>'...
[11:58:11] Starting 'assets'...
[11:58:11] Starting 'scripts'...
[11:58:11] Starting 'styles'...
error TS5024: Compiler option 'isolatedModules' requires a value of type boolean.
error TS5024: Compiler option 'outFile' requires a value of type string.
[11:58:13] 'scripts' errored after 1.11 s
[11:58:13] Error: File not found with singular glob: /Users/guybedford/Projects/test/angular2-blank-project/typings/browser.d.ts
    at Glob.<anonymous> (/Users/guybedford/Projects/test/angular2-blank-project/node_modules/glob-stream/index.js:39:11)
    at Glob.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at Glob.emit (events.js:188:7)
    at Glob._finish (/Users/guybedford/Projects/test/angular2-blank-project/node_modules/glob-stream/node_modules/glob/glob.js:172:8)
    at done (/Users/guybedford/Projects/test/angular2-blank-project/node_modules/glob-stream/node_modules/glob/glob.js:159:12)
    at Glob._processSimple2 (/Users/guybedford/Projects/test/angular2-blank-project/node_modules/glob-stream/node_modules/glob/glob.js:652:12)
    at /Users/guybedford/Projects/test/angular2-blank-project/node_modules/glob-stream/node_modules/glob/glob.js:640:10
    at Glob._stat2 (/Users/guybedford/Projects/test/angular2-blank-project/node_modules/glob-stream/node_modules/glob/glob.js:736:12)
    at lstatcb_ (/Users/guybedford/Projects/test/angular2-blank-project/node_modules/glob-stream/node_modules/glob/glob.js:728:12)
    at RES (/Users/guybedford/Projects/test/angular2-blank-project/node_modules/inflight/inflight.js:23:14)
    at f (/Users/guybedford/Projects/test/angular2-blank-project/node_modules/once/once.js:17:25)
    at FSReqWrap.oncomplete (fs.js:117:15)
```

**Comment by unlight** [comment]
Is file `typings/browser.d.ts` exists? If not, it seems that `npm i` failed, and postinstall was not triggered.
Try manual `typings i` or just create empty file.

**Comment by guybedford** [comment]
Unfortunately it's still not working for me here eg - 

```
error TS5024: Compiler option 'isolatedModules' requires a value of type boolean.
error TS5024: Compiler option 'outFile' requires a value of type string.
[15:59:34] styles all files 185.45 kB
[15:59:34] Finished 'assets' after 2.83 s
[15:59:35] Finished 'styles' after 3.16 s
/Users/guybedford/Projects/test/angular2-blank-project/node_modules/@angular/testing/src/matchers.d.ts(4,37): error TS2503: Cannot find namespace 'jasmine'.
/Users/guybedford/Projects/test/angular2-blank-project/node_modules/@angular/testing/src/test_component_builder.d.ts(26,19): error TS2314: Generic type 'ComponentRef<C>' requires 1 type argument(s).
```
