### ISSUE TITLE
jspm import throws an error

### ISSUE THREAD

**Issue by tomeraz** [systemjs/systemjs#1279]
Hey @guybedford,
Using jspm@0.17.0-beta.14
When trying to import jspm inside a node module I get an error.
Anything I should install so it could work?
Thanks!
### Code
```
import jspm from 'jspm'
```
### Error
```
err  path.js:7
      throw new TypeError('Path must be a string. Received ' + inspect(path));
      ^
  TypeError: Path must be a string. Received undefined
      at assertPath (path.js:7:11)
      at Object.dirname (path.js:1324:5)
      at Object.<anonymous> (/Users/tomer/code/playground/jspm-nisuy/jspm_packages/npm/traceur@0.0.105/src/node/traceur.js:19:27)
      at /Users/tomer/code/playground/jspm-nisuy/jspm_packages/npm/traceur@0.0.105/src/node/traceur.js:37:4
      at Object.exports.runInThisContext (vm.js:54:17)
      at SystemJSNodeLoader.__exec (/Users/tomer/code/playground/jspm-nisuy/node_modules/jspm/node_modules/systemjs/dist/system.src.js:1514:12)
      at entry.execute (/Users/tomer/code/playground/jspm-nisuy/node_modules/jspm/node_modules/systemjs/dist/system.src.js:3979:18)
      at linkDynamicModule (/Users/tomer/code/playground/jspm-nisuy/node_modules/jspm/node_modules/systemjs/dist/system.src.js:3292:32)
      at getModule (/Users/tomer/code/playground/jspm-nisuy/node_modules/jspm/node_modules/systemjs/dist/system.src.js:3260:9)
      at /Users/tomer/code/playground/jspm-nisuy/node_modules/jspm/node_modules/systemjs/dist/system.src.js:3296:16
      at require (/Users/tomer/code/playground/jspm-nisuy/node_modules/jspm/node_modules/systemjs/dist/system.src.js:3946:29)
      at Object.<anonymous> (/Users/tomer/code/playground/jspm-nisuy/jspm_packages/npm/traceur@0.0.105/src/node/api.js:23:15)
      at /Users/tomer/code/playground/jspm-nisuy/jspm_packages/npm/traceur@0.0.105/src/node/api.js:61:4
      at Object.exports.runInThisContext (vm.js:54:17)
      at SystemJSNodeLoader.__exec (/Users/tomer/code/playground/jspm-nisuy/node_modules/jspm/node_modules/systemjs/dist/system.src.js:1514:12)
      at entry.execute (/Users/tomer/code/playground/jspm-nisuy/node_modules/jspm/node_modules/systemjs/dist/system.src.js:3979:18)
      at linkDynamicModule (/Users/tomer/code/playground/jspm-nisuy/node_modules/jspm/node_modules/systemjs/dist/system.src.js:3292:32)
      at link (/Users/tomer/code/playground/jspm-nisuy/node_modules/jspm/node_modules/systemjs/dist/system.src.js:3135:11)
      at Object.execute (/Users/tomer/code/playground/jspm-nisuy/node_modules/jspm/node_modules/systemjs/dist/system.src.js:3473:13)
      at doDynamicExecute (/Users/tomer/code/playground/jspm-nisuy/node_modules/jspm/node_modules/systemjs/dist/system.src.js:798:25)
      at link (/Users/tomer/code/playground/jspm-nisuy/node_modules/jspm/node_modules/systemjs/dist/system.src.js:1000:20)
      at doLink (/Users/tomer/code/playground/jspm-nisuy/node_modules/jspm/node_modules/systemjs/dist/system.src.js:652:7)
  Evaluating /Users/tomer/code/playground/jspm-nisuy/jspm_packages/npm/traceur@0.0.105/src/node/traceur.js
  Evaluating /Users/tomer/code/playground/jspm-nisuy/jspm_packages/npm/traceur@0.0.105/src/node/api.js
  Error loading /Users/tomer/code/playground/jspm-nisuy/server.js
```

**Comment by guybedford** [comment]
Importing jspm

**Comment by guybedford** [comment]
This is double posted right?

**Comment by tomeraz** [comment]
Yes, I couldn't tell if the problem is related to jspm or systemjs.
