### ISSUE TITLE
SystemJS unable to load

### ISSUE THREAD

**Issue by sqlsolver** [systemjs/systemjs#1367]
There is a SystemJS error when trying to load reflect-metadata. I have imported reflect-metadata first as suggested here [https://github.com/rbuckton/ReflectDecorators/issues/15](url) and also added it to system.config. I've looked at the accordion component and it seems to be written the same way as the other components in that package, so I believe the problem is in loading reflect-metadata. Error is:

`Error: (SystemJS) TypeError: Reflect.getOwnMetadata is not a function
	    at PropDecorator (http://easyofficeforms.com/easyOfficeForms/node_modules/@angular/core/bundles/core.umd.js:2817:40)
	    at __decorate (http://easyofficeforms.com/easyOfficeForms/node_modules/ng2-bootstrap/components/accordion/accordion.component.js:5:110)
	    at eval (http://easyofficeforms.com/easyOfficeForms/node_modules/ng2-bootstrap/components/accordion/accordion.component.js:39:5)
	    at Object.eval (http://easyofficeforms.com/easyOfficeForms/node_modules/ng2-bootstrap/components/accordion/accordion.component.js:55:2)
	    at eval (http://easyofficeforms.com/easyOfficeForms/node_modules/ng2-bootstrap/components/accordion/accordion.component.js:58:4)
	    at eval (http://easyofficeforms.com/easyOfficeForms/node_modules/ng2-bootstrap/components/accordion/accordion.component.js:59:3)
	Evaluating http://easyofficeforms.com/easyOfficeForms/node_modules/ng2-bootstrap/components/accordion/accordion.component.js
	Evaluating http://easyofficeforms.com/easyOfficeForms/node_modules/ng2-bootstrap/components/accordion.js
	Evaluating http://easyofficeforms.com/easyOfficeForms/node_modules/ng2-bootstrap/ng2-bootstrap.js
	Error loading http://easyofficeforms.com/easyOfficeForms/app/EOFapp.ts`

[http://easyofficeforms.com](url) is the URL and the git repo has been shared with you.

**Comment by sqlsolver** [comment]
Put together another app with only two differences, left out ng2-bootstrap and used the newest router. Leaving out ng2-bootstrap there are no issues with SystemJS loading the app and I think the problem is likely in ng2-bootstrap so will move this issue there.
