### ISSUE TITLE
Getting "SyntaxError: Multiple definitions of a property not allowed in strict mode" on IE11

### ISSUE THREAD

**Issue by atrauzzi** [systemjs/systemjs#1436]
I apologize if this isn't the right project to reporting this bug, it is however being generated by SystemJS:

```
Potentially unhandled rejection [3] (SystemJS) Multiple definitions of a property not allowed in strict mode
	SyntaxError: Multiple definitions of a property not allowed in strict mode
	   at ee (http://localhost/Content/jspm_packages/system.js:4:21944)
	   at Anonymous function (http://localhost/Content/jspm_packages/system.js:5:9664)
	   at Anonymous function (http://localhost/Content/jspm_packages/system.js:5:14324)
	   at Anonymous function (http://localhost/Content/jspm_packages/system.js:5:17599)
	   at Anonymous function (http://localhost/Content/jspm_packages/system.js:5:21955)
	   at Anonymous function (http://localhost/Content/jspm_packages/system.js:5:24928)
	   at Anonymous function (http://localhost/Content/jspm_packages/system.js:4:10809)
	Evaluating http://localhost/Content/src/App/EditEvent/Component/Section/Tickets/Component.tsx
	Error loading http://localhost/Content/src/App/EditEvent/Component/Section/Tickets/Component.tsx as "./Section/Tickets/Component.tsx" from http://localhost/Content/s
```

I guess my issue is twofold:

 - I can't find a duplicate declaration anywhere in this file
 - This exception message is being truncated, so I'm having a tricky time narrowing down what's going on

**Comment by guybedford** [comment]
This does sound like a case of `var obj = { prop: 'x', prop: 'duplicate' }` in Component.tsx.

**Comment by atrauzzi** [comment]
@guybedford - Phew! Well, it wasn't lying about the duplicate key :D

Although it kind of sucks that IE11 was truncating the error.  I wonder if it would have given me a line number if it didn't get eaten...?
