### ISSUE TITLE
Virtual window/document globals for dependencies in NodeJS-based unit tests?

### ISSUE THREAD

**Issue by clintharris** [systemjs/systemjs#1479]
I'm using SystemJS 0.19.29 and have implemented NodeJS-based Mocha unit tests using the methods described at http://guybedford.com/systemjs-mocha-istanbul (i.e., using a variant of the custom test runner example there).

As soon as my unit test imports something that depends on jQuery (i.e., one of my UI widgets), I get the following error:

```
TypeError: Cannot read property 'createElement' of undefined
  at assert (/myapp/jspm_packages/npm/jquery@2.2.0/dist/jquery.js:901:20)
  ...
  Evaluating /myapp/jspm_packages/npm/jquery@2.2.0/dist/jquery.js
```

I've been trying to figure out how to get jQuery to use a headless browser object coming from [jsdom](https://github.com/tmpvar/jsdom) but haven't had any luck and woudl appreciate any tips.

I've tried a temporary config override to inject the jsdom globals as a shim, like this (`runner.js` based on http://guybedford.com/systemjs-mocha-istanbul):
```
var jsdom = require('jsdom').jsdom;
var document = jsdom('');
System.set('fake-window', System.newModule({ document: document, window: document.defaultView }));

SystemJS.import('./system.config.js')
  .then(() => {
    SystemJS.config({
      // Override the "vendor.js" bundle specified in `system.config.js` with an empty array since we don't need the
      // bundle when running tests. This helps speed things up and allows us to avoid some other SystemJS issues related
      // to 3rd-party modules not working in our unit test setup for some reason.
      bundles: { "vendor.js": [] },
      shim: {
        "npm:jquery@2.2.0/dist/jquery.js": {
          "globals": {
            "window": "fake-window",
            "document": "fake-window"
          }
        }
      }
    });
  // ... load and run tests
```

I've also tried just setting the jsdom-based window/document variables in `runner.js` _before_ the unit tests run, like this:
```
var jsdom = require('jsdom').jsdom;
var document = jsdom('');
global.document = document;
global.window = document.defaultView;

SystemJS.import('./system.config.js')
  .then(() => {
  // ... load and run tests
```

But this seems to break something else related to Babel:

```
Error: ReferenceError: babel is not defined
      at /myapp/jspm_packages/npm/babel-core@5.8.38/browser.js:68452:19
      at Object.exports.runInThisContext (vm.js:54:17)
      at Object.<anonymous> (/myapp/jspm_packages/npm/babel-core@5.8.38.js:1:123)
      at /myapp/jspm_packages/npm/babel-core@5.8.38.js:2:4
  Evaluating /myapp/jspm_packages/npm/babel-core@5.8.38/browser.js
  Evaluating /myapp/jspm_packages/npm/babel-core@5.8.38.js
  Error loading /myapp/jspm_packages/npm/babel-core@5.8.38.js
  Error loading /myapp/test/FooComponent.test.js
```

Any pro tips on how to get browser-dependent stuff like jQuery to use virtual window/document variables?

**Comment by guybedford** [comment]
It's possible to set globals for execution of other modules via the `globals` configuration:

```javascript
System.config({
  meta: {
    'path/to/jquery.js': {
      globals: {
        window: 'custom-global.js'
      }
    }
  }
});
```

Where `custom-global.js` is just say:

```javascript
module.exports = global;
```

Something along those lines may help here.
