### ISSUE TITLE
jsdom support for systemjs@0.20

### ISSUE THREAD

**Issue by unional** [systemjs/systemjs#1581]
Continuing the journey for https://github.com/systemjs/systemjs/issues/1578

I find out why my code in https://github.com/unional/some-issues/tree/systemjs-jsdomify works in `index.html` and not in test, using `jsdomify`.

The issue is that `jsdomify` set `document.baseURI` to `about:blank`, which cause `es-module-loader` resolves `baseURI` is resolved to `/`

type | document.baseURI | (es-module-loader) baseURI
-----|--------------------|-----------------------------
jsdomify | about:blank | /
server | http://localhost:3000/ | http://localhost:3000/
file:// | file:///Users/....../some-issues/index.html | file:///Users/....../some-issues/

That's why it ended up with this error:
```sh
Error: Unable to resolve "/./plugins/npm-module/node_modules//./plugins/npm-module" to /
  Resolving npm-module
  Loading npm-module
    throwResolveError (node_modules/systemjs/node_modules/es-module-loader/core/resolve.js:9:1)
    resolveIfNotPlain (node_modules/systemjs/dist/system.src.js:147:9)
    SystemJSLoader$1.coreResolve (node_modules/systemjs/src/resolve.js:199:4)
    node_modules/systemjs/dist/system.src.js:1783:34
```

(By the way, I wonder the correctness of "/./plugins/npm-module/node_modules//./plugins/npm-module", it seems wrong but working when running with `localhost`).

When I try to overcome this by specifying `<base>` tag:

```js
const jsdomify = require('jsdomify').default
jsdomify.create('<!DOCTYPE html><html><base href="file:///Users/hwong/github/unional/some-issues/index.html"></html>'
```

It gives me a different error:

```sh
Error: XHR error:  loading file:///Users/hwong/github/unional/some-issues/plugins/npm-module/package.json
  Instantiating file:///Users/hwong/github/unional/some-issues/plugins/npm-module/package.json
  Loading file:///Users/hwong/github/unional/some-issues/plugins/npm-module/package.json
  Unable to fetch package configuration file file:///Users/hwong/github/unional/some-issues/plugins/npm-module/package.json
  Resolving npm-module
  Loading npm-module
    XMLHttpRequest.error (node_modules/systemjs/src/fetch.js:57:14)
    invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:210:27)
    EventTargetImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:130:9)
    EventTargetImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:91:17)
    XMLHttpRequest.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:71:35)
    dispatchError (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:915:9)
    validCORSHeaders (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:930:7)
    receiveResponse (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:805:12)
    EventEmitter.client.on.res (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:626:38)
    process.nextTick (node_modules/jsdom/lib/jsdom/living/xhr-utils.js:96:35)
```

What's strange about this is the path is actually correct, but fail to load the file.
UPDATE: This part looks more like a `jsdom` issue. Filed issue over there regarding this.

UPDATE QUESTION: Should `about:blank` be "supported"? Or adding the `<base>` is the right approach?

**Comment by unional** [comment]
FYI, I have updated the test code so that it runs both the node version and jsdom version to see the difference.
Also added `npm run serve` to demo that it is working in browser:

```sh
npm run serve
# for mac
open http://localhost:3000
```

**Comment by unional** [comment]
Also, I have change the code to load `color-map` so that it won't run into the browser spec issue (to keep things simpler).

Also, have changed the config to:
```ts
  const sys = new SystemJS.constructor()
  sys.config({
    baseURL: `plugins`,
    map: {
      [pluginName]: pluginName,
      'color-map': pluginName + '/node_modules/color-map'
      // '*': './npm-module/node_modules/*'
    },
    packageConfigPaths: [
      '*/package.json',
      pluginName + '/node_modules/*/package.json',
      pluginName + '/node_modules/@*/*/package.json'
    ]
  })
```

This is an attempt to fix the weird `/./plugins/npm-module/node_modules//./plugins/npm-module` path.
it is working in node and browser like that.
But if I change it to:

```ts
  const sys = new SystemJS.constructor()
  sys.config({
    baseURL: `plugins`,
    map: {
      [pluginName]: pluginName,
      // 'color-map': pluginName + '/node_modules/color-map'
      '*': './npm-module/node_modules/*'
    },
    packageConfigPaths: [
      '*/package.json',
      pluginName + '/node_modules/*/package.json',
      pluginName + '/node_modules/@*/*/package.json'
    ]
  })
```

It fails (on node) with:
```sh
Error: ENOENT: no such file or directory, open '/Users/hwong/github/unional/some-issues/plugins/color-map/package.json'
  Instantiating /Users/hwong/github/unional/some-issues/plugins/color-map/package.json
  Loading /Users/hwong/github/unional/some-issues/plugins/color-map/package.json
  Unable to fetch package configuration file /Users/hwong/github/unional/some-issues/plugins/color-map/package.json
  Resolving color-map to /Users/hwong/github/unional/some-issues/plugins/npm-module/src/index.js
  Loading /Users/hwong/github/unional/some-issues/plugins/npm-module/src/index.js
  Loading npm-module
```

And fails on browser with:
```sh
GET http://localhost:3000/plugins/color-map/package.json 404 (Not Found)
fetchFetch @ fetch.js:41
(anonymous) @ instantiate.js:176
common.js:83 Uncaught (in promise) Error: Fetch error: 404 Not Found
  Instantiating http://localhost:3000/plugins/color-map/package.json
  Loading http://localhost:3000/plugins/color-map/package.json
  Unable to fetch package configuration file http://localhost:3000/plugins/color-map/package.json
  Resolving color-map to http://localhost:3000/plugins/npm-module/src/index.js
  Loading http://localhost:3000/plugins/npm-module/src/index.js
  Loading npm-module
    at fetch.js:46
```

So the map is somehow messed up.

**Comment by guybedford** [comment]
@unional `*` is not supported in map configuration, so that may explain the confusion with the pathing.

As for the XHR issue, that sounds like a security restriction in jsdom not to allow XHR fetching of file:/// URLs. I've added a fix in https://github.com/ModuleLoader/es-module-loader/commit/5d6b70a8a1c407b24badd644e48de4823e514fd9 for the baseURI detection. It would be worth sticking with the `<base>` tag approach until that is out, but perhaps a different base URL is needed in jsdom if it isn't going to support file URLs.

**Comment by unional** [comment]
For `/./plugins/npm-module/node_modules//./plugins/npm-module`, it is not coming from the usage of `*` thou.

The original config that produce this path is:

```ts
const pluginName = 'npm-module'
  const sys = new SystemJS.constructor()
  sys.config({
    baseURL: `plugins/${pluginName}/node_modules`,
    map: {
      [pluginName]: './plugins/' + pluginName
    },
    packageConfigPaths: [
      './plugins/*/package.json',
      '*/package.json',
      '@*/*/package.json'
    ]
  })
```
So it seems like `baseURL/map['npm-module']` produce that path.
Maybe that's a separate issue?

**Comment by unional** [comment]
Tested with your latest change. Seems like the path issue is "resolved". The current error (without `<base>`) is:

```sh
Promise rejected with: { Error: XHR error:  loading about:blank/plugins/npm-module/package.json
    at XMLHttpRequest.error (about:blank:1454:14)
    at invokeEventListeners (/Users/hwong/github/unional/some-issues/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:219:27)
    at EventTargetImpl._dispatch (/Users/hwong/github/unional/some-issues/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:126:9)
    at EventTargetImpl.dispatchEvent (/Users/hwong/github/unional/some-issues/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
    at XMLHttpRequest.dispatchEvent (/Users/hwong/github/unional/some-issues/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:61:35)
    at dispatchError (/Users/hwong/github/unional/some-issues/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:994:9)
    at EventEmitter.client.on.err (/Users/hwong/github/unional/some-issues/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:688:11)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at process.nextTick (/Users/hwong/github/unional/some-issues/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:236:37)
  originalErr:
   Error: XHR error:  loading about:blank/plugins/npm-module/package.json
       at XMLHttpRequest.error (about:blank:1454:14)
       at invokeEventListeners (/Users/hwong/github/unional/some-issues/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:219:27)
       at EventTargetImpl._dispatch (/Users/hwong/github/unional/some-issues/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:126:9)
       at EventTargetImpl.dispatchEvent (/Users/hwong/github/unional/some-issues/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:
17)
       at XMLHttpRequest.dispatchEvent (/Users/hwong/github/unional/some-issues/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:61:35)
       at dispatchError (/Users/hwong/github/unional/some-issues/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:994:9)
       at EventEmitter.client.on.err (/Users/hwong/github/unional/some-issues/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:688:11)
       at emitOne (events.js:101:20)
       at EventEmitter.emit (events.js:188:7)
       at process.nextTick (/Users/hwong/github/unional/some-issues/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:236:37) }
  invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:219:27)
  EventTargetImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:126:9)
  EventTargetImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
  XMLHttpRequest.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:61:35)
  dispatchError (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:994:9)
  EventEmitter.client.on.err (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:688:11)
  process.nextTick (node_modules/jsdom/lib/jsdom/living/xhr-utils.js:236:37)
   Error: XHR error:  loading about:blank/plugins/npm-module/package.json
     XMLHttpRequest.error (about:blank:1454:14)
     invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:219:27)
     EventTargetImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:126:9)
     EventTargetImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
     XMLHttpRequest.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:61:35)
     dispatchError (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:994:9)
     EventEmitter.client.on.err (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:688:11)
     process.nextTick (node_modules/jsdom/lib/jsdom/living/xhr-utils.js:236:37) }
```

So the `baseURI` is there "correctly". 😛

**Comment by guybedford** [comment]
@unional at this point I think it is a jsdom configuration problem to ensure that you are setting the environment URL and enabling URL requests.

**Comment by unional** [comment]
Agree. Is it ok to keep this issue open until it is resolved on the `jsdom` side?

**Comment by guybedford** [comment]
I think the issue here is just configuring jsdom. From what I can tell XHR
in jsdom requires setting up a custom URL and resource loader. The custom
URL allows the base URI not to be about:blank, and the resource loader
allows enabling xhr as far as I can tell looking at this briefly.

Alternatively set SystemJS to use the script load mode over xhr.

The custom resource loader is covered in the main readme for jsdom and
should be as in the example there to implement.

**Comment by unional** [comment]
> From what I can tell XHR in jsdom requires setting up a custom URL

Yes, this is essentially the issue.
The solution for me is:

```ts
import { env } from 'jsdom'

env({
  file: 'index.html'
  scripts: [
    require.resolve('<script files I want to load>'),
    require.resolve('<script files I want to load>')
  ],
  done(err, win) {
    ...
  }
})
```
