### ISSUE TITLE
ZoneAwareError

### ISSUE THREAD

**Issue by phansontu** [systemjs/systemjs#1598]
I got this error - ZoneAwareError - when I upgrade my system.js from 0.19.40 to 0.20.9.

This is console error

```
ZoneAwareError__zone_symbol__error: Error: Unexpected token <
  Evaluating http://localhost:3001//angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js
  Evaluating http://localhost:3001//main.js
  Loading app
    at LoaderError__Check_error_message_for_loader_stack (http://localhost:3001/systemjs/dist/system.src.js:80:11) [<root>]
    at http://localhost:3001/systemjs/dist/system.src.js:284:11 [<root>]
    at Zone.run (http://localhost:3001/zone.js/dist/zone.js:126:43) [<root> => <root>]
    at http://localhost:3001/zone.js/dist/zone.js:679:57 [<root>]
    at Zone.runTask (http://localhost:3001/zone.js/dist/zone.js:166:47) [<root> => <root>]
    at drainMicroTaskQueue (http://localhost:3001/zone.js/dist/zone.js:529:35) [<root>]__zone_symbol__stack: "SyntaxError: Unexpected token <↵    at eval (<anonymous>)↵    at evaluate (http://localhost:3001/systemjs/dist/system.src.js:2788:16)↵    at http://localhost:3001/systemjs/dist/system.src.js:3604:21↵    at dynamicExecute (http://localhost:3001/systemjs/dist/system.src.js:1158:26)↵    at doEvaluate (http://localhost:3001/systemjs/dist/system.src.js:1102:13)↵    at ensureEvaluate (http://localhost:3001/systemjs/dist/system.src.js:1011:13)↵    at http://localhost:3001/systemjs/dist/system.src.js:1031:20↵    at Object.eval (http://localhost:3001//main.js:3:34)↵    at eval (http://localhost:3001//main.js:7:4)↵    at eval (http://localhost:3001//main.js:8:3)↵    at eval (<anonymous>)↵    at evaluate (http://localhost:3001/systemjs/dist/system.src.js:2788:16)↵    at http://localhost:3001/systemjs/dist/system.src.js:3569:21↵    at dynamicExecute (http://localhost:3001/systemjs/dist/system.src.js:1158:26)↵    at doEvaluate (http://localhost:3001/systemjs/dist/system.src.js:1102:13)"message: (...)name: (...)originalErr: SyntaxError: Unexpected token <
    at eval (<anonymous>)
    at evaluate (http://localhost:3001/systemjs/dist/system.src.js:2788:16)
    at http://localhost:3001/systemjs/dist/system.src.js:3604:21
    at dynamicExecute (http://localhost:3001/systemjs/dist/system.src.js:1158:26)
    at doEvaluate (http://localhost:3001/systemjs/dist/system.src.js:1102:13)
    at ensureEvaluate (http://localhost:3001/systemjs/dist/system.src.js:1011:13)
    at http://localhost:3001/systemjs/dist/system.src.js:1031:20
    at Object.eval (http://localhost:3001//main.js:3:34)
    at eval (http://localhost:3001//main.js:7:4)
    at eval (http://localhost:3001//main.js:8:3)
    at eval (<anonymous>)
    at evaluate (http://localhost:3001/systemjs/dist/system.src.js:2788:16)
    at http://localhost:3001/systemjs/dist/system.src.js:3569:21
    at dynamicExecute (http://localhost:3001/systemjs/dist/system.src.js:1158:26)
    at doEvaluate (http://localhost:3001/systemjs/dist/system.src.js:1102:13)originalStack: (...)stack: (...)toSource: ()toString: ()zoneAwareStack: (...)get message: ()set message: (value)get name: ()set name: (value)get originalStack: ()set originalStack: (value)get stack: ()set stack: (value)get zoneAwareStack: ()set zoneAwareStack: (value)__proto__: Object
(anonymous) @ login:20
ZoneDelegate.invoke @ zone.js:330
Zone.run @ zone.js:126
(anonymous) @ zone.js:679
ZoneDelegate.invokeTask @ zone.js:363
Zone.runTask @ zone.js:166
drainMicroTaskQueue @ zone.js:529
```

**Comment by phansontu** [comment]
I had configured my system.config.js to available to expressjs and maybe, that changes were not run with new system.config.js
I realized that when cloning new angular seed. So I think I can research by myself. Thanks
