### ISSUE TITLE
typescript.js detected as amd but didn't execute correctly

### ISSUE THREAD

**Issue by pdhar-tibco** [systemjs/systemjs#1599]
I am getting this with systemjs version 0.20.9 with angular 2.4.8 and typescript 2.0.2 and 2.2.1
```
ZoneAwareError
__zone_symbol__error
:
Error: Module https://unpkg.com/typescript@2.0.2/lib/typescript.js detected as amd but didn't execute correctly. Instantiating https://unpkg.com/typescript@2.0.2/lib/typescript.js Loading typescript Unable to load transpiler to transpile https://run.plnkr.co/IYynm0lUzr0pBSBd/src/main.ts Instantiating https://run.plnkr.co/IYynm0lUzr0pBSBd/src/main.ts Loading app at t (https://unpkg.com/systemjs@0.20.9/dist/system.js:4:221) [<root>] at https://unpkg.com/systemjs@0.20.9/dist/system.js:5:4728 [<root>] at Zone.run (https://unpkg.com/zone.js@0.7.7/dist/zone.js:126:43) [<root> => <root>] at https://unpkg.com/zone.js@0.7.7/dist/zone.js:679:57 [<root>] at Zone.runTask (https://unpkg.com/zone.js@0.7.7/dist/zone.js:166:47) [<root> => <root>] at drainMicroTaskQueue (https://unpkg.com/zone.js@0.7.7/dist/zone.js:529:35) [<root>]
message
:
"Module https://unpkg.com/typescript@2.0.2/lib/typescript.js detected as amd but didn't execute correctly.↵  Instantiating https://unpkg.com/typescript@2.0.2/lib/typescript.js↵  Loading typescript↵  Unable to load transpiler to transpile https://run.plnkr.co/IYynm0lUzr0pBSBd/src/main.ts↵  Instantiating https://run.plnkr.co/IYynm0lUzr0pBSBd/src/main.ts↵  Loading app"
originalStack
:
"Error: Module https://unpkg.com/typescript@2.0.2/lib/typescript.js detected as amd but didn't execute correctly.↵  Instantiating https://unpkg.com/typescript@2.0.2/lib/typescript.js↵  Loading typescript↵  Unable to load transpiler to transpile https://run.plnkr.co/IYynm0lUzr0pBSBd/src/main.ts↵  Instantiating https://run.plnkr.co/IYynm0lUzr0pBSBd/src/main.ts↵  Loading app↵    at ZoneAwareError (https://unpkg.com/zone.js@0.7.7/dist/zone.js:958:33)↵    at t (https://unpkg.com/systemjs@0.20.9/dist/system.js:4:221)↵    at https://unpkg.com/systemjs@0.20.9/dist/system.js:5:4728↵    at ZoneDelegate.invoke (https://unpkg.com/zone.js@0.7.7/dist/zone.js:330:26)↵    at Zone.run (https://unpkg.com/zone.js@0.7.7/dist/zone.js:126:43)↵    at https://unpkg.com/zone.js@0.7.7/dist/zone.js:679:57↵    at ZoneDelegate.invokeTask (https://unpkg.com/zone.js@0.7.7/dist/zone.js:363:31)↵    at Zone.runTask (https://unpkg.com/zone.js@0.7.7/dist/zone.js:166:47)↵    at drainMicroTaskQueue (https://unpkg.com/zone.js@0.7.7/dist/zone.js:529:35)"
stack
:
"Error: Module https://unpkg.com/typescript@2.0.2/lib/typescript.js detected as amd but didn't execute correctly.↵  Instantiating https://unpkg.com/typescript@2.0.2/lib/typescript.js↵  Loading typescript↵  Unable to load transpiler to transpile https://run.plnkr.co/IYynm0lUzr0pBSBd/src/main.ts↵  Instantiating https://run.plnkr.co/IYynm0lUzr0pBSBd/src/main.ts↵  Loading app↵    at t (https://unpkg.com/systemjs@0.20.9/dist/system.js:4:221) [<root>]↵    at https://unpkg.com/systemjs@0.20.9/dist/system.js:5:4728 [<root>]↵    at Zone.run (https://unpkg.com/zone.js@0.7.7/dist/zone.js:126:43) [<root> => <root>]↵    at https://unpkg.com/zone.js@0.7.7/dist/zone.js:679:57 [<root>]↵    at Zone.runTask (https://unpkg.com/zone.js@0.7.7/dist/zone.js:166:47) [<root> => <root>]↵    at drainMicroTaskQueue (https://unpkg.com/zone.js@0.7.7/dist/zone.js:529:35) [<root>]"
zoneAwareStack
:
"Error: Module https://unpkg.com/typescript@2.0.2/lib/typescript.js detected as amd but didn't execute correctly.↵  Instantiating https://unpkg.com/typescript@2.0.2/lib/typescript.js↵  Loading typescript↵  Unable to load transpiler to transpile https://run.plnkr.co/IYynm0lUzr0pBSBd/src/main.ts↵  Instantiating https://run.plnkr.co/IYynm0lUzr0pBSBd/src/main.ts↵  Loading app↵    at t (https://unpkg.com/systemjs@0.20.9/dist/system.js:4:221) [<root>]↵    at https://unpkg.com/systemjs@0.20.9/dist/system.js:5:4728 [<root>]↵    at Zone.run (https://unpkg.com/zone.js@0.7.7/dist/zone.js:126:43) [<root> => <root>]↵    at https://unpkg.com/zone.js@0.7.7/dist/zone.js:679:57 [<root>]↵    at Zone.runTask (https://unpkg.com/zone.js@0.7.7/dist/zone.js:166:47) [<root> => <root>]↵    at drainMicroTaskQueue (https://unpkg.com/zone.js@0.7.7/dist/zone.js:529:35) [<root>]"
__proto__
```

Here is the plunker sample https://plnkr.co/edit/EEz16F?p=preview

**Comment by baumann** [comment]
I am having the same problem, when trying to get 'd3' working with Angular2.

**Comment by unional** [comment]
One funny thing is `SystemJS.import('systemjs')` also have this issue. 🌷

**Comment by frankwallis** [comment]
@pdhar-tibco have you tried using [plugin-typescript](https://github.com/frankwallis/plugin-typescript)?

**Comment by zixia** [comment]
I run into this issue today when I updating a 6-months old workable repository.

After I use the latest SystemJS & TypeScript, this error appeared.

**Comment by guybedford** [comment]
See https://github.com/systemjs/systemjs/issues/1587#issuecomment-287013920.
