### ISSUE TITLE
Cannot import mqtt

### ISSUE THREAD

**Issue by Florimond** [systemjs/systemjs#1601]
I create a minimalist aurelia install based on instructions from [How to set up minimal Aurelia project from scratch](http://stackoverflow.com/questions/32080221/how-to-set-up-minimal-aurelia-project-from-scratch)

I then install mqtt with :

```
jspm install npm:mqtt
```

Then add the following line in the *app.js*.
```
import mqtt from 'mqtt';
```

Which results in the following error :

```
Error: (SystemJS) Cannot read property 'prototype' of undefined
	TypeError: Cannot read property 'prototype' of undefined
	    at inherits (http://localhost:9000/jspm_packages/npm/inherits@2.0.3/inherits_browser.js:6:45)
	    at Object.eval (http://localhost:9000/jspm_packages/npm/websocket-stream@3.3.3/server.js:24:1)
	    at eval (http://localhost:9000/jspm_packages/npm/websocket-stream@3.3.3/server.js:26:4)
	    at eval (http://localhost:9000/jspm_packages/npm/websocket-stream@3.3.3/server.js:27:3)
	    at eval (<anonymous>)
	Evaluating http://localhost:9000/jspm_packages/npm/websocket-stream@3.3.3/server.js
	Evaluating http://localhost:9000/jspm_packages/npm/websocket-stream@3.3.3/index.js
	Evaluating http://localhost:9000/jspm_packages/npm/websocket-stream@3.3.3.js
	Evaluating http://localhost:9000/jspm_packages/npm/mqtt@2.4.0/lib/connect/ws.js
	Evaluating http://localhost:9000/jspm_packages/npm/mqtt@2.4.0/lib/connect/index.js
	Evaluating http://localhost:9000/jspm_packages/npm/mqtt@2.4.0/mqtt.js
	Evaluating http://localhost:9000/jspm_packages/npm/mqtt@2.4.0.js
	Error loading http://localhost:9000/app.js
	    at inherits (http://localhost:9000/jspm_packages/npm/inherits@2.0.3/inherits_browser.js:6:45)
	    at Object.eval (http://localhost:9000/jspm_packages/npm/websocket-stream@3.3.3/server.js:24:1)
	    at eval (http://localhost:9000/jspm_packages/npm/websocket-stream@3.3.3/server.js:26:4)
	    at eval (http://localhost:9000/jspm_packages/npm/websocket-stream@3.3.3/server.js:27:3)
	    at eval (<anonymous>)
	Evaluating http://localhost:9000/jspm_packages/npm/websocket-stream@3.3.3/server.js
	Evaluating http://localhost:9000/jspm_packages/npm/websocket-stream@3.3.3/index.js
	Evaluating http://localhost:9000/jspm_packages/npm/websocket-stream@3.3.3.js
	Evaluating http://localhost:9000/jspm_packages/npm/mqtt@2.4.0/lib/connect/ws.js
	Evaluating http://localhost:9000/jspm_packages/npm/mqtt@2.4.0/lib/connect/index.js
	Evaluating http://localhost:9000/jspm_packages/npm/mqtt@2.4.0/mqtt.js
	Evaluating http://localhost:9000/jspm_packages/npm/mqtt@2.4.0.js
	Error loading http://localhost:9000/app.js
  ```
![alt](https://raw.githubusercontent.com/Florimond/aurelia-mqtt-issue/master/inherits%20websocketserver.png)

![alt](https://github.com/Florimond/aurelia-mqtt-issue/blob/master/require%20ws-fallback.png?raw=true)

**Here is my repo demonstrating the issue :** https://github.com/Florimond/aurelia-mqtt-issue/

* **Aurelia Framework Version:**
1.0.8

* **Operating System:**
Windows 10

* **Node Version:**
6.9.5

* **NPM Version:**
3.10.10

* **JSPM OR Webpack AND Version**
JSPM 0.19.46

* **Browser:**
all

**Comment by guybedford** [comment]
Did you make any progress on this?

**Comment by florimond-gaming1** [comment]
Unfortunately none.
On the github of MQTT, I was told it was an issue with Aurelia. On the github of Aurelia github, I was told it was an issue with systemjs.
I haven't got any answers on Stackoverflow either. 

I'm not a web developer, so I was hoping to get some help from someone more knowledgeable that me.

**Comment by Florimond** [comment]
Unfortunately none.
On the github of MQTT, I was told it was an issue with Aurelia. On the github of Aurelia, I was told it was an issue with systemjs.
I haven't got any answers on Stackoverflow either.

I'm not a web developer, so I was hoping to get some help from someone more knowledgeable than me.

**Comment by guybedford** [comment]
@Florimond it looks like you are using jspm 0.16... did you try using 0.17?

**Comment by Florimond** [comment]
@guybedford I installed  jspm 0.17 with...

```
npm install -g jspm@beta1
```

Then I followed the same instructions to setup a minimalist aurelia install, except for this part :

> Enable all the fancy cutting edge babel goodness by adding the following line to the babelOptions in your config.js (jspm init created the config.js file):
```
System.config({
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "stage": 0,      <------ add this to turn on the hotness
    "optional": [
      "runtime"
    ]
  },
````
...since this file seems to have been replaced with a **jspm.config.js** and seems to have a slightly different structure.

I haven't tried to install mqtt yet, because I already have the following error when I try to launch the app :

```
Error: XHR error:  loading file:///D:/test-aurelia170319/aurelia-bootstrapper
  Instantiating file:///D:/test-aurelia170319/aurelia-bootstrapper
  Loading aurelia-bootstrapper  system.js:4
```
