### ISSUE TITLE
SystemJS does not work well with NPM link

### ISSUE THREAD

**Issue by ORESoftware** [systemjs/systemjs#1653]
I have a project that I want to "browserify". The project is modularized, and is composed of other projects on the filesystem. To develop these projects in tandem, I use NPM link. When I try to build with the SystemJS builder, I get errors like this:

```
Build error (Ensure that this module sits within the baseURL or a wildcard path config)

{ Error tracing node_modules/suman-browser-polyfills/modules/all-core-and-npm.js at file:///Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/suman-browser-polyfills/modules/all-core-and-npm.js
        Error: Unable to calculate canonical name to bundle file:///Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman-debug/index.js. **Ensure that this module sits within the baseURL or a wildcard path config**.
    at getCanonicalNamePlain (/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/systemjs-builder/lib/utils.js:227:13)
    at getCanonicalName (/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/systemjs-builder/lib/utils.js:150:19)
    at /Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/systemjs-builder/lib/trace.js:548:36
  originalErr: 
   Error: Unable to calculate canonical name to bundle file:///Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman-debug/index.js. Ensure that this module sits within the baseURL or a wildcard path config.
       at getCanonicalNamePlain (/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/systemjs-builder/lib/utils.js:227:13)
       at getCanonicalName (/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/systemjs-builder/lib/utils.js:150:19)
       at /Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/systemjs-builder/lib/trace.js:548:36 }
```

**Comment by ORESoftware** [comment]
This is the configuration I am using:


```js
let path = require('path');
let Builder = require('systemjs-builder');
const pkg = require('./package.json');
const deps = pkg.dependencies;


const polyfills = [
  'fs',
  'process',
  'global'
];

function getPaths() {
  return Object.map(deps, function (k, v) {
    if(polyfills.includes(k)){
      return require.resolve('suman-browser-polyfills/modules/' + k);
    }
    return require.resolve(k);
  });
}

function getMap(){
  return Object.map(deps, function (k, v) {
    let val;
    if(polyfills.includes(k)){
      val = require.resolve('suman-browser-polyfills/modules/' + k);
    }
    else{
      val = require.resolve(k);
    }
    
    return val;
  });
}

let builder = new Builder(__dirname, {
  // paths: getPaths(),
  defaultJSExtensions: true,
  map: getMap()
});

let src = path.resolve(__dirname + '/node_modules/suman-browser-polyfills/modules/all-core-and-npm.js');
console.log('src => ', src);

let dest = path.resolve(__dirname + '/dist/outfile.js');

builder
.bundle(src, dest)
.then(function () {
  console.log('Build complete');
})
.catch(function (err) {
  console.log('Build error');
  console.log(err);
});
```

If it's not clear what the problem is, I can try to clarify, I am looking for a solution to this problem.

**Comment by guybedford** [comment]
@ORESoftware for "browserify" use cases it's probably best to use a build tool configured with node_modules resolution. jspm can do this for SystemJS builder, otherwise I'd suggest browserify or webpack.
