### ISSUE TITLE
Issue with modules exports when Vue used

### ISSUE THREAD

**Issue by ArmorDarks** [systemjs/systemjs#1814]
As its title, issue is quite enigmatic for me.

## How to reproduce

I've created [a repository, where the issue can be reproduced](https://github.com/ArmorDarks/_del-vue-modules-issue) 

Clone repository, install dependencies

Run

```shell
 jspm build main test.js
```

## What happens

Following error will be thrown:

```
 jspm build main test.js
     Creating the single-file build for main...

err  SyntaxError: source/scripts/main.js: Unexpected token, expected ; (6:8)
  4 |   computed: Object.assign({}, {}),
  5 |
> 6 |   render: function render() {}
    |         ^
  7 | };
  8 |
    at Parser.pp$5.raise (J:\Work\Greencard\_del-test\node_modules\babylon\lib\index.js:4454:13)
    at Parser.pp.unexpected (J:\Work\Greencard\_del-test\node_modules\babylon\lib\index.js:1761:8)
    at Parser.pp.semicolon (J:\Work\Greencard\_del-test\node_modules\babylon\lib\index.js:1742:38)
    at Parser.pp$1.parseExpressionStatement (J:\Work\Greencard\_del-test\node_modules\babylon\lib\index.js:2236:8)
    at Parser.pp$1.parseStatement (J:\Work\Greencard\_del-test\node_modules\babylon\lib\index.js:1911:17)
    at Parser.pp$1.parseLabeledStatement (J:\Work\Greencard\_del-test\node_modules\babylon\lib\index.js:2228:20)
    at Parser.pp$1.parseStatement (J:\Work\Greencard\_del-test\node_modules\babylon\lib\index.js:1909:17)
    at Parser.pp$1.parseBlockBody (J:\Work\Greencard\_del-test\node_modules\babylon\lib\index.js:2268:21)
    at Parser.pp$1.parseBlock (J:\Work\Greencard\_del-test\node_modules\babylon\lib\index.js:2247:8)
    at Parser.pp$1.parseStatement (J:\Work\Greencard\_del-test\node_modules\babylon\lib\index.js:1868:19)
    at Parser.pp$1.parseBlockBody (J:\Work\Greencard\_del-test\node_modules\babylon\lib\index.js:2268:21)
    at Parser.pp$1.parseTopLevel (J:\Work\Greencard\_del-test\node_modules\babylon\lib\index.js:1778:8)
    at Parser.parse (J:\Work\Greencard\_del-test\node_modules\babylon\lib\index.js:1673:17)
    at parse (J:\Work\Greencard\_del-test\node_modules\babylon\lib\index.js:7305:37)
    at File.parse (J:\Work\Greencard\_del-test\node_modules\babel-core\lib\transformation\file\index.js:517:15)
    at File.parseCode (J:\Work\Greencard\_del-test\node_modules\babel-core\lib\transformation\file\index.js:602:20)
```

After testing, I've discovered that if `/source/scripts/App.js` content will be changed

```diff

- export default {
+ module.exrpots = {
    computed: Object.assign({}, {}),
  
    render () {}
  }

```

and `main.js` changed to

```diff
import Vue from 'vue'
- import App from './App'
+ const App = require('./App')
```

build passes without errors

Probably, for some reason SystemJS tries to read `App.js` as non-ES6 module, and thus can't parse `export default {}`

Strangely enough, removing `Object.assign` from `App.js` for some reason fixes the issue too:

```diff
  export default {
-   computed: Object.assign({}, {}),
+   computed: {},
  
    render () {}
  }
```

As well as removing `Vue` from `main.js`:

```diff
- import Vue from 'vue'
  import App from './App'
```

which doesn't make any sense to me. Maybe Vue somehow affecting loader and mutates other modules format, or something is wrong with SystemJS module detecting regex?

## What expected to happen

Well, expected to build without errors.

**Comment by guybedford** [comment]
This is very odd. In the error message you provided it looks like it is attempting to parse the source as if it were a block with a labelled statement. Which makes me think perhaps the `export default` part has been somehow removed so that Babylon is just seeing `{ computed: computed: Object.assign({}, {}), render: function render() {} }`. Ideally you'd want to debug the Babylon parse call itself to see what source is being passed into Babylon here. If the source is right it may be a Babylon bug.

The Vue case looks very odd though as well.

**Comment by ArmorDarks** [comment]
Issue resolved by beta.48. I don't know why, though.
