### ISSUE TITLE
SystemJS not working with IE11

### ISSUE THREAD

**Issue by kouts** [systemjs/systemjs#1844]
SystemJS does not work with IE11.
It seems that the issue is the ```startsWith``` method used here: https://github.com/systemjs/systemjs/blob/b3ec782c3e15bdb8d056975528f67caf0e211bdf/src/instantiate.js#L426

Pollyfilling ```startsWith``` fixed the issue.

**Comment by kouts** [comment]
I have created a PR which solves the issue.
https://github.com/systemjs/systemjs/pull/1845

**Comment by ponnusamyas** [comment]
SystemJS does not work with IE11. 
IE 11 have below exception 

Error: (SystemJS) Unable to get property 'length' of undefined or null reference
	TypeError: Unable to get property 'length' of undefined or null reference
	   at g (http://localhost:9108/node_modules/core-js/client/shim.min.js:8:10014)
	   at Anonymous function (http://localhost:9108/node_modules/core-js/client/shim.min.js:8:10138)
	   at k (http://localhost:9108/node_modules/core-js/client/shim.min.js:8:14293)
	Error loading http://localhost:9108/main.js
   {
      description: "(SystemJS) Unable to get property 'length' of undefined or null reference
	TypeError: Unable to get property 'length' of undefined or null reference
	   at g (http://localhost:9108/node_modules/core-js/client/shim.min.js:8:10014)
	   at Anonymous function (http://10.100.4.38:9108/node_modules/core-js/client/shim.min.js:8:10138)
	   at k (http://localhost:9108/node_modules/core-js/client/shim.min.js:8:14293)
	Error loading http://localhost:9108/main.js",
      name: "Error",
      originalErr: {
         description: "Unable to get property 'length' of undefined or null reference",
         name: "TypeError",
         number: -2146823281,
         stack: "TypeError: Unable to get property 'length' of undefined or null reference
   at Anonymous function (http://localhost:9108/node_modules/systemjs/dist/system.src.js:5026:27)
   at Anonymous function (http://10.100.4.38:9108/node_modules/systemjs/dist/system.src.js:5101:7)
   at Anonymous function (http://10.100.4.38:9108/node_modules/systemjs/dist/system.src.js:391:9)
   at g (http://10.100.4.38:9108/node_modules/core-js/client/shim.min.js:8:10014)
   at Anonymous function (http://10.100.4.38:9108/node_modules/core-js/client/shim.min.js:8:10138)
   at k (http://10.100.4.38:9108/node_modules/core-js/client/shim.min.js:8:14293)"
      },
      stack: "(SystemJS) Unable to get property 'length' of undefined or null reference
	TypeError: Unable to get property 'length' of undefined or null reference
	   at g (http://10.100.4.38:9108/node_modules/core-js/client/shim.min.js:8:10014)
	   at Anonymous function (http://10.100.4.38:9108/node_modules/core-js/client/shim.min.js:8:10138)
	   at k (http://10.100.4.38:9108/node_modules/core-js/client/shim.min.js:8:14293)
	Error loading http://10.100.4.38:9108/main.js"
   }

{
   description: "Unable to get property 'length' of undefined or null reference",
   name: "TypeError",
   number: -2146823281,
   stack: "TypeError: Unable to get property 'length' of undefined or null reference
   at Anonymous function (http://localhost:9108/node_modules/systemjs/dist/system.src.js:5026:27)
   at Anonymous function (http://localhost:9108/node_modules/systemjs/dist/system.src.js:5101:7)
   at Anonymous function (http://localhost:9108/node_modules/systemjs/dist/system.src.js:391:9)
   at g (http://localhost:9108/node_modules/core-js/client/shim.min.js:8:10014)
   at Anonymous function (http://localhost:9108/node_modules/core-js/client/shim.min.js:8:10138)
   at k (http://localhost:9108/node_modules/core-js/client/shim.min.js:8:14293)"
}

**Comment by guybedford** [comment]
Fixed in 0.21.5.
