### ISSUE TITLE
npm install systemjs  : throw error on Win10

### ISSUE THREAD

**Issue by pritisolanki** [systemjs/systemjs#1944]
Tried
```
npm install systemjs
```
and got

```
npm ERR! node v10.15.3
npm ERR! npm  v3.9.0
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (C:\Users\user\AppData\Roaming\npm\node_modules\npm\lib\fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (C:\Users\user\AppData\Roaming\npm\node_modules\npm\lib\fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (C:\Users\user\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:490:12)
npm ERR! typeerror     at C:\Users\user\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:225:5
npm ERR! typeerror     at C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
npm ERR! typeerror     at Array.forEach (<anonymous>)
npm ERR! typeerror     at C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
npm ERR! typeerror     at Array.forEach (<anonymous>)
npm ERR! typeerror     at asyncMap (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)

npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
```

The repo highlighted is marked as read only so can't raise the ticket as well.

Any help would be appreciated.

**Comment by joeldenning** [comment]
I don't know exactly why it's throwing an error, but is [this line](https://github.com/nodejs/node/blob/master/deps/npm/lib/fetch-package-metadata.js#L51) of help?

It looks like npm is getting confused -- it's trying to install a package with `C:\` in the path, but it thinks that it's not in a Windows environment. Perhaps this could be related to using WSL or a VM or something else that's confusing node? You could also try upgrading/downgrading node to see if it's related to node 10
