### ISSUE TITLE
How to import and how to export in systemjs

### ISSUE THREAD

**Issue by inspiraller** [systemjs/systemjs#2401]
- SystemJS Version: 
//cdn.jsdelivr.net/npm/systemjs/dist/system.js

- Which extras are you using?
?
- Are you using any [custom hooks](/docs/hooks.md)?
?

### Question
After scouring examples online and experimenting I have NOT found a simple explanation of how to import/export files.
How is it possible to achieve the below, with systemjs in the browser?
See example:
**index.html**
```
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible” content=”IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>test import</title>
</head>

<body>
  <script type="systemjs-importmap">
    {
      "imports": {
        "main": "/js/main.js"
      }
    }
  </script>

  <script src="/js/hello.js"></script>
  <script type="systemjs-module" src="import:main"></script>
  <script src="//cdn.jsdelivr.net/npm/systemjs/dist/system.js"></script>
</body>

</html>
```
**hello.js**
```
export const hello = (name) => `hello: ${name}`;
```

**main.js**
```
import {hello} from 'helllo.js'
const result = hello('john');
console.log('result')
export default {data: result};
```

**Comment by nilzona** [comment]
```html
<script type="systemjs-importmap">
    {
      "imports": {
        // NOT NEEDED, REMOVE
        "main": "/js/main.js"
        // INSTEAD ADD THIS
        "hello": "/js/hello.js"
      }
    }
  </script>

<-! REMOVE THIS LINE -->
  <script src="/js/hello.js"></script>
<-! REMOVE THIS LINE -->

  <script type="systemjs-module" src="import:main"></script>
  <script src="//cdn.jsdelivr.net/npm/systemjs/dist/system.js"></script>
```

your `hello.js` either needs to be rewritten as a [SystemJS module](https://github.com/systemjs/systemjs/blob/main/docs/system-register.md) or you will need a transpiler with webpack that sets the output target to `system`.

Then you will need to use your import like this:
```js
import { hello } from "hello"; // hello will be mapped to "/js/hello.js" with the import-map
```

**Comment by inspiraller** [comment]
@nilzona  Thanks for the example.
ok this is what I've updated as your suggestion but getting error:

**server.js**
```
app.use('/', express.static(__dirname + '/html'));
```

**dir:**
```
html/
  index.html
  js/
    hello.js
    main.js
```


**index.html**
```html
<!doctype html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible” content=”IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="/css/global.css" rel="stylesheet" />
  <title>test import</title>
</head>

<body>
  <div id="app">
    code goes here...
  </div>
  <script type="systemjs-importmap">
    {
      "imports": {
        "hello": "/js/hello.js"
      }
    }
  </script>
  <script type="systemjs-module" src="import:main"></script>
  <script src="//cdn.jsdelivr.net/npm/systemjs/dist/system.js"></script>
</body>

</html>
```

**js/main.js**
```js
import {hello} from 'hello'
const result = hello('john');
console.log('result')
export default {data: result};
```

**js/hello.js**
```js
export const hello = (name) => `hello: ${name}`;
```

> Error: 
system.js:702 Uncaught (in promise) Error: Unable to resolve bare specifier 'main' from http://localhost:8080/ (SystemJS Error#8 https://git.io/JvFET#8)
    at throwUnresolved (system.js:702:11)
    at systemJSPrototype.resolve (system.js:698:101)
    at system.js:227:21
