### ISSUE TITLE
Uncaught ReferenceError: System is not defined

### ISSUE THREAD

**Issue by maurya2711** [systemjs/systemjs#2440]
hey Folks,

I need to make my existing Vue 2 project into single-spa project. I am using  Following packages and their version:
    * Vue 2.7.13
    * system-webpack-interope 2.3.7
    * single-spa-vue  2.5.1

here it is my vue config file
![image](https://user-images.githubusercontent.com/50194244/197315250-1ccf987a-3f16-4ab7-a3d3-3d5763c20f01.png)

so when i run this project this gave me this error

![image](https://user-images.githubusercontent.com/50194244/197315317-47c2a54f-d92c-415f-b9e7-c2ca0045409f.png)

**Comment by nilzona** [comment]
If `System` is not defined it has not been loaded. Do you have a script tag in your html like below?

```html
<script src="https://cdn.jsdelivr.net/npm/systemjs/dist/system.js"></script>
```

**Comment by pierrybos** [comment]
I have the same error. 

`<script src="https://cdn.jsdelivr.net/npm/systemjs/dist/system.js"></script>
            <script src="https://www.gstatic.com/firebasejs/9.0.1/firebase-app.js"></script>
            <script src="https://www.gstatic.com/firebasejs/9.0.1/firebase-messaging.js"></script>
            
            <script>
  SystemJS.import('./js/nofity.js').catch(console.error);
</script>`

and the error is:


`Uncaught SyntaxError: Unexpected token 'export' (at firebase-app.js:1590:1)
firebase-messaging.js:1 Uncaught SyntaxError: Cannot use import statement outside a module (at firebase-messaging.js:1:1)
ReferenceError: SystemJS is not defined
    at index.php:13:1`

**Comment by nilzona** [comment]
Try to use `System.import` instead of `SystemJS.import`

there seem to be some error also in the firebase code that I don't know anything about.

**Comment by Simran-Mudaliar** [comment]
I'm encountering a similar issue locally when building and serving the root application using Docker Desktop. 
![image](https://github.com/single-spa/single-spa/assets/158295542/c76a93ee-5729-492c-bc40-00922d6e825e)
When inspecting the browser console, I notice that the issue arises when the application attempts to execute the line System.import('@org/root-config') within my index.ejs file. This line imports the root-config file from the path "@org/root-config": "//localhost:4400/org-root-config.js".

I downloaded the package and saved it to a folder named public (I know this isn't the best practice, but I was trying different methods to load the packages). In my index.ejs file, I'm importing it with the following line
<script src="public/system.min.js" crossorigin="anonymous"></script>
