### ISSUE TITLE
Illegal Module Name

### ISSUE THREAD

**Issue by marcfallows** [systemjs/systemjs#247]
I'm not sure if this belongs here or the es6-module-loader, but if I do the following:

``` javascript
require(["http://some.domain.com/script.js"], function(script){
   //...
});
```

I get the following error:
`TypeError: Illegal module name "http://some.domain.com/script.js"`

Full stack trace:

```
 TypeError: Illegal module name "http://some.domain.com/script.js"
    at v.$__Object$defineProperty.value (http://this.domain.com/lib/es6-module-loader/0.9.4/es6-module-loader.js:7:26099)
    at v.$__global.upgradeSystemLoader.e.normalize (http://this.domain.com/lib/system/0.9.3/system.js:1:15350)
    at v.$__global.upgradeSystemLoader.e.normalize (http://this.domain.com/lib/system/0.9.3/system.js:1:15680)
    at v.$__global.upgradeSystemLoader.e.normalize (http://this.domain.com/lib/system/0.9.3/system.js:1:19899)
    at v.import (http://this.domain.com/lib/es6-module-loader/0.9.4/es6-module-loader.js:7:20460)
    at v.$__global.upgradeSystemLoader.e.import (http://this.domain.com/lib/system/0.9.3/system.js:1:7114)
    at http://this.domain.com/lib/system/0.9.3/system.js:1:12140
    at Array.map (native)
    at v.a [as amdRequire] (http://this.domain.com/lib/system/0.9.3/system.js:1:12106)
    at $__global.upgradeSystemLoader.string.i (http://this.domain.com/lib/system/0.9.3/system.js:1:12278)
```

Is this expected behaviour? The same would work with RequireJS.

**Comment by OliverJAsh** [comment]
We have also come up against the issue of invalid module IDs when requesting absolute URLs. In my view, how exactly the module is downloaded (XHR/script) is a separate issue. Instead, I want to ask if absolute URLs could be valid module IDs?

**Comment by guybedford** [comment]
So the new spec will be supporting this, but the old one didn't.

I'm going to be posting an intermediate release with the non-breaking changes in the new spec, and should be able to include this feature with that.
