### ISSUE TITLE
Node stacktraces

### ISSUE THREAD

**Issue by arcanis** [systemjs/systemjs#278]
Here is the kind of errors that I get when using SystemJS with Node:

```
arcanis@~/project/server # authbind --deep willikins --profile profiles/dev run
TypeError: object is not a function
    at eval (eval at __eval (/home/arcanis/willikins/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader-sans-promises.src.js:1518:105), <anonymous>:58:20)
    at Array.forEach (native)
    at socialLinks (eval at __eval (/home/arcanis/willikins/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader-sans-promises.src.js:1518:105), <anonymous>:57:16)
    at getComplexApp (eval at __eval (/home/arcanis/willikins/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader-sans-promises.src.js:1518:105), <anonymous>:53:13)
    at eval (eval at __eval (/home/arcanis/willikins/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader-sans-promises.src.js:1518:105), <anonymous>:122:25)
    at /home/arcanis/willikins/node_modules/systemjs/node_modules/es6-module-loader/node_modules/traceur/bin/traceur.js:620:32
    at Object.asyncWrap (/home/arcanis/willikins/node_modules/systemjs/node_modules/es6-module-loader/node_modules/traceur/bin/traceur.js:613:5)
    at eval (eval at __eval (/home/arcanis/willikins/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader-sans-promises.src.js:1518:105), <anonymous>:117:32)
    at Function.eval (eval at __eval (/home/arcanis/willikins/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader-sans-promises.src.js:1518:105), <anonymous>:48:37)
    at /home/arcanis/willikins/node_modules/systemjs/node_modules/es6-module-loader/node_modules/traceur/bin/traceur.js:620:32
```

With some training it's possible to find the related line, but it's still pretty hard, and sometimes I have to put some console.log into SystemJS to find the right trigger spots.

I don't know if the issue comes from Node itself, ES6 Module Loader or SystemJS, but I have seen that apparently SystemJS should generate sourcemap, so I try my luck here :)

I've also tried using the [node-source-map-support](https://github.com/evanw/node-source-map-support) module, but it didn't work (exceptions hanged).

**Comment by guybedford** [comment]
@arcanis if you still have the example and a follow-up do let me know. Closing for now though.
