### ISSUE TITLE
SystemJS code breaking in PhantomJS

### ISSUE THREAD

**Issue by Zensavona** [systemjs/systemjs#440]
Hi guys, I'm trying to get my code running in Phantom to run some tests, but it's breaking and I'm not exactly sure why.

It's an Aurelia/SystemJS based app and both my application and an Aurelia example using SystemJS break with Phantom. Here are the outputs from both:

[app-contacts](https://github.com/aurelia/app-contacts):

````
CONSOLE: INFO [aurelia] Aurelia Starting (from line #undefined in "undefined")
CONSOLE: DEBUG [aurelia] Loading plugin github:aurelia/templating-binding@0.11.0. (from line #undefined in "undefined")
TypeError: Attempting to define property on object that is not extensible.

  http://localhost:9001/:48 in defineProperty
  http://localhost:9001/:36
  http://localhost:9001/:29 in fastKey
  http://localhost:9001/:115
  http://localhost:9001/:10 in set
  http://localhost:9001/:51 in set
  http://localhost:9001/:14 in ensureOriginOnExports
  http://localhost:9001/:131
  http://localhost:9001/jspm_packages/es6-module-loader.js:7 in O
  http://localhost:9001/jspm_packages/es6-module-loader.js:7 in K
  http://localhost:9001/jspm_packages/es6-module-loader.js:7
  http://localhost:9001/jspm_packages/es6-module-loader.js:7
  http://localhost:9001/jspm_packages/es6-module-loader.js:7
  http://localhost:9001/jspm_packages/es6-module-loader.js:7
````

my application:

````
CONSOLE: Potentially unhandled rejection [2] ReferenceError: Can't find variable: Map
    at http://127.0.0.1:8380/web-admin/:22
    at p (http://127.0.0.1:8380/web-admin/jspm_packages/system.js:1)
    at p (http://127.0.0.1:8380/web-admin/jspm_packages/system.js:1)
    at p (http://127.0.0.1:8380/web-admin/jspm_packages/system.js:1)
    at p (http://127.0.0.1:8380/web-admin/jspm_packages/system.js:1)
    at p (http://127.0.0.1:8380/web-admin/jspm_packages/system.js:1)
    at p (http://127.0.0.1:8380/web-admin/jspm_packages/system.js:1)
    at p (http://127.0.0.1:8380/web-admin/jspm_packages/system.js:1)
    at http://127.0.0.1:8380/web-admin/jspm_packages/system.js:1
    at o (http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7)
    at p (http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7)
    at j (http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7)
    at k (http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7)
    at http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7
    at O (http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7)
    at K (http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7)
    at http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7
    at http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7
    at http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7
    at http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7 (from line #undefined in "undefined")
````
FWIW these both work fine in Chrome/FF and I'm running PhantomJS 1.9.8 on OS X 10.10

Also here's the phantom script I am using to test these and output from the console:
````
var webPage = require('webpage');
var page = webPage.create();

page.open('http://localhost:9001/', function() {
  page.onConsoleMessage = function(msg, lineNum, sourceId) {
    console.log('CONSOLE: ' + msg + ' (from line #' + lineNum + ' in "' + sourceId + '")');
  };
});
````

I've made some instructions to replicate the first set of errors:
````
git clone git@github.com:aurelia/app-contacts.git
cd app-contacts
npm install && jspm install
gulp watch
````
This assumes you have `node`, `jspm` and `gulp` installed. Then you can run the above phantomjs script.

**Comment by guybedford** [comment]
@Zensavona have you tried running PhantomJS 2 here?

**Comment by Zensavona** [comment]
I haven't @guybedford, it's not on npm yet and attempting to install it has proven difficult. Do you think that is likely a/the cause?

**Comment by Zensavona** [comment]
I got PhantomJS 2 running (`phantomjs2` npm package, who would of thought...) and am now getting an even more cryptic error.

````
Potentially unhandled rejection [2] 	at execute (http://127.0.0.1:8380/web-admin/:22:30)
	at p (http://127.0.0.1:8380/web-admin/jspm_packages/system.js:1:9364)
	at p (http://127.0.0.1:8380/web-admin/jspm_packages/system.js:1:9296)
	at p (http://127.0.0.1:8380/web-admin/jspm_packages/system.js:1:9296)
	at p (http://127.0.0.1:8380/web-admin/jspm_packages/system.js:1:9296)
	at p (http://127.0.0.1:8380/web-admin/jspm_packages/system.js:1:9296)
	at p (http://127.0.0.1:8380/web-admin/jspm_packages/system.js:1:9296)
	at p (http://127.0.0.1:8380/web-admin/jspm_packages/system.js:1:9296)
	at execute (http://127.0.0.1:8380/web-admin/jspm_packages/system.js:1:18339)
	at o (http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7:44413)
	at p (http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7:44779)
	at j (http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7:42325)
	at k (http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7:42710)
	at http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7:55365
	at O (http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7:12117)
	at K (http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7:11746)
	at when (http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7:15420)
	at run (http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7:14459)
	at _drain (http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7:3232)
	at drain (http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7:1653)

  http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7
````

**Comment by guybedford** [comment]
It may be advisable to use the unminified versions of SystemJS / ES6 Module Loader for debugging here.

Then can you confirm if you're able to have SystemJS load, or run a simple test script? It may be worth starting small instead of trying to load your whole app.

**Comment by Zensavona** [comment]
Don't worry - I've moved my tests out of Phantom as they run in all major browsers without issue, unfortunately I don't have the time to delve into this. Closing this issue, thanks for the help.

**Comment by micaelmbagira** [comment]
I have one issue quite similar. I have a phantom test (I use [node-horseman](https://github.com/johntitus/node-horseman)) to test a AngularJS app. The test fails because the angular code is not evaluated and the following error is returned:

````
[Error message] Potentially unhandled rejection [2] 
    forEach
    loadModules
    createInjector
    doBootstrap
    bootstrap
    angularInit

    j@phantomjs://code/jquery-2.1.1.min.js:2:27129
    add@phantomjs://code/jquery-2.1.1.min.js:2:54127
    ready@phantomjs://code/jquery-2.1.1.min.js:2:29543

    eval code
    eval@[native code]
    W@http://localhost:3000/jspm_packages/system.js:4:40570
    execute@http://localhost:3000/jspm_packages/system.js:5:12260
    u@http://localhost:3000/jspm_packages/system.js:5:7837
    r@http://localhost:3000/jspm_packages/system.js:5:6387
    execute@http://localhost:3000/jspm_packages/system.js:5:11458
    y@http://localhost:3000/jspm_packages/system.js:4:21990
    w@http://localhost:3000/jspm_packages/system.js:4:22363
    p@http://localhost:3000/jspm_packages/system.js:4:20241
    h@http://localhost:3000/jspm_packages/system.js:4:20626
    http://localhost:3000/jspm_packages/system.js:4:27580
    Evaluating http://localhost:3000/jspm_packages/npm/angular@1.5.3/angular.js
    Error loading http://localhost:3000/src/index.js
[Error trace] [ { file: 'http://localhost:3000/jspm_packages/system-polyfills.js',
    line: 4,
    function: '' } ]
````
You can easily reproduce the issue by cloning this project https://github.com/micaelmbagira/horseman-replication
