### ISSUE TITLE
TypeError: Cannot read property 'match' of undefined when calling System.import from node

### ISSUE THREAD

**Issue by capaj** [systemjs/systemjs#486]
I have a gulp process which would like to load a config file. There is a bunch of them, but only one gets loaded in my frontend app.
So I import the config.js and set baseURL and then call System.import like this:
```javascript
require('../src/config.js');
  System.baseURL = './src/';
  return System.import('ENV')
```
I get this error thrown:
```
 TypeError: Cannot read property 'match' of undefined
    at Loader.loader.translate (C:\projects\cdm-fe\node_modules\jspm\node_modules\systemjs\dist\system.src.js:264:27)
    at Loader.loader.translate (C:\projects\cdm-fe\node_modules\jspm\node_modules\systemjs\dist\system.src.js:751:44)
    at Loader.loader.translate (C:\projects\cdm-fe\node_modules\jspm\node_modules\systemjs\dist\system.src.js:936:28)
    at Loader.loader.translate (C:\projects\cdm-fe\node_modules\jspm\node_modules\systemjs\dist\system.src.js:1819:30)
    at C:\projects\cdm-fe\node_modules\systemjs\dist\system.src.js:328:47
    at tryCatchReject (C:\projects\cdm-fe\node_modules\jspm\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:1183:30)
    at runContinuation1 (C:\projects\cdm-fe\node_modules\jspm\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:1142:4)
    at Fulfilled.when (C:\projects\cdm-fe\node_modules\jspm\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:930:4)
    at Pending.run (C:\projects\cdm-fe\node_modules\jspm\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:821:13)
    at Scheduler._drain (C:\projects\cdm-fe\node_modules\jspm\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:97:19)
```

I went and tried to add a check whether it is a string or not to all the places, where load.source is being matched, but that only got me an error in:

```
[10:28:35] TypeError: Cannot read property 'length' of undefined
    at new Scanner (C:\projects\cdm-fe\node_modules\jspm\node_modules\traceur\bin\traceur.js:10404:29)
    at new Parser (C:\projects\cdm-fe\node_modules\jspm\node_modules\traceur\bin\traceur.js:11478:23)
    at Compiler.parse (C:\projects\cdm-fe\node_modules\jspm\node_modules\traceur\bin\traceur.js:29769:22)
    at Object.exports.compile (C:\projects\cdm-fe\node_modules\jspm\node_modules\systemjs-builder\compilers\global.js:98:23)
    at C:\projects\cdm-fe\node_modules\jspm\node_modules\systemjs-builder\lib\compile.js:26:43
    at lib$rsvp$$internal$$tryCatch (C:\projects\cdm-fe\node_modules\jspm\node_modules\rsvp\dist\rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (C:\projects\cdm-fe\node_modules\jspm\node_modules\rsvp\dist\rsvp.js:501:17)
    at C:\projects\cdm-fe\node_modules\jspm\node_modules\rsvp\dist\rsvp.js:1095:13
    at lib$rsvp$asap$$flush (C:\projects\cdm-fe\node_modules\jspm\node_modules\rsvp\dist\rsvp.js:1290:9)
    at doNTCallback0 (node.js:408:9)

```

My system.js installed in node_modules is 0.17.1, but the one actually being executed is the one from node_modules\jspm\node_modules\systemjs which is version 0.16.11.

**Comment by capaj** [comment]
oh I should not have submitted this, this error I get is from the bundle gulp task which got broken by me setting the System.baseURL. My mistake. Closing.

**Comment by MikeJoyce19** [comment]
@capaj how did you solve this? Would you mind posting your config in relation to baseURL and lib?
