### ISSUE TITLE
Building modules with arithmetic expressions in module name breaks build process

### ISSUE THREAD

**Issue by jamiehill** [systemjs/systemjs#583]
Hi Guy, as said before a million times - fantastic work!

I'm trying to bundle some specific modules, who's name/s may contain `systemjs-builder` arithmetic operators, which appears to confuse the building process.  

For example:

```
return Promise.all([
   builder.trace('react & core-js')
])
.then(function(trees) {
   return Promise.all([
      builder.build(trees[0], 'modules.js')
   ]);
});
```

This results - when building, in:

```
Error: Expected operator before Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:129:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/jamie/Sites/WebApp/git/mybet/mybet-sportsbook/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/jamie/Sites/WebApp/git/mybet/mybet-sportsbook/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/jamie/Sites/WebApp/git/mybet/mybet-sportsbook/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at /Users/jamie/Sites/WebApp/git/mybet/mybet-sportsbook/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:45:4
    at lib$rsvp$$internal$$tryCatch (/Users/jamie/Sites/WebApp/git/mybet/mybet-sportsbook/node_modules/systemjs-builder/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/jamie/Sites/WebApp/git/mybet/mybet-sportsbook/node_modules/systemjs-builder/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/jamie/Sites/WebApp/git/mybet/mybet-sportsbook/node_modules/systemjs-builder/node_modules/rsvp/dist/rsvp.js:472:11)
```

I may be barking up the wrong tree, but is the `-` in `core-js`, being interpretted as a substract?

My main objective here is ultimately excluding certain module trees from the bundle file.  When adding modules without the operator, this seems to work as I'd hoped.  I have seen somewhere else, an api for explicitly excluding modules, but can't seem to find now, and think it may have been depreciated in `SystemJs 0.17`

**Comment by guybedford** [comment]
Thanks, it always means a lot to hear positive feedback. Try using `trees[0].tree` in the `builder.build` operation here, as the trace object isn't the direct buildable tree itself.

**Comment by jamiehill** [comment]
Ok Guy, will give that a shot ...

(super quick response by the by!)

**Comment by guybedford** [comment]
Sure, just let me know if you need further help here at all!
