### ISSUE TITLE
Dependencies of dependencies not being loaded, defaultExtension: "ts"-related?

### ISSUE THREAD

**Issue by nicklasb** [systemjs/systemjs#721]
So I am continuing to try to get my "defaultExtension": "ts"-TypeScript-base project running, and after #720, I have encountered another problem: 
Imports within `github:OptimalBPM/mbe-nodes@0.4.10/dist/nodes.ts` doesn't resolve properly. 

For example, `import "angular-strap` in `nodes.ts` causes SystemJS to look at `http://localhost:63342/optimalbpm/optimalbpm/broker/ui/angular-strap.js`.

If I add `"angular-strap": "github:mgcrea/angular-strap@2.3.1"` to the top-level it works, but I was under the impression that one shouldn't have to.

The error:
``` 
Uncaught (in promise) Error: XHR error (404 Not Found) loading http://localhost:63342/optimalbpm/optimalbpm/broker/ui/angular-strap.js
	Error loading http://localhost:63342/optimalbpm/optimalbpm/broker/ui/angular-strap.js as "angular-strap" from http://localhost:63342/optimalbpm/optimalbpm/broker/ui/jspm_packages/github/OptimalBPM/mbe-nodes@0.4.10/dist/nodes.ts
    at error (http://localhost:63342/optimalbpm/optimalbpm/broker/ui/jspm_packages/system.src.js:1028:16)
    at XMLHttpRequest.xhr.onreadystatechange (http://localhost:63342/optimalbpm/optimalbpm/broker/ui/jspm_packages/system.src.js:1036:13)
```
My config:

```js

System.config({
  defaultJSExtensions: true,
  transpiler: "typescript",
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },

  packages: {
    "scripts": {
      "defaultExtension": "ts"
    },
    "controllers": {
      "defaultExtension": "ts"
    },
    "directives": {
      "defaultExtension": "ts"
    },
    "github:OptimalBPM/mbe-nodes@0.4.10": {
      "defaultExtension": "ts",
      "map": {
        "mbe-nodes": "github:OptimalBPM/mbe-nodes@0.4.10"
      }
    }
  },

  map: {
    "angular": "github:angular/bower-angular@1.4.4",
    "angular-animate": "github:angular/bower-angular-animate@1.4.4",
    "angular-route": "github:angular/bower-angular-route@1.4.4",
    "angular-sanitize": "github:angular/bower-angular-sanitize@1.4.4",
    "angular-touch": "github:angular/bower-angular-touch@1.4.4",
    "angular-ui-layout": "github:angular-ui/ui-layout@1.0.5",
    "angular-ui-select": "github:angular-ui/ui-select@0.12.1",
    "bootstrap": "github:twbs/bootstrap@3.3.5",
    "bootstrap3-dialog": "github:nakupanda/bootstrap3-dialog@1.34.5",
    "css": "github:systemjs/plugin-css@0.1.13",
    "jquery": "github:components/jquery@2.1.4",
    "mbe-nodes": "github:OptimalBPM/mbe-nodes@0.4.10",
    "traceur": "github:jmcriffey/bower-traceur@0.0.91",
    "traceur-runtime": "github:jmcriffey/bower-traceur-runtime@0.0.91",
    "typescript": "npm:typescript@1.6.0-dev.20150824",
    "github:OptimalBPM/mbe-nodes@0.4.10": {
      "angular": "github:angular/bower-angular@1.4.4",
      "angular-animate": "github:angular/bower-angular-animate@1.4.4",
      "angular-route": "github:angular/bower-angular-route@1.4.4",
      "angular-sanitize": "github:angular/bower-angular-sanitize@1.4.4",
      "angular-schema-form": "npm:angular-schema-form@0.8.7",
      "angular-schema-form-dynamic-select": "npm:angular-schema-form-dynamic-select@0.11.6",
      "angular-strap": "github:mgcrea/angular-strap@2.3.1",
      "angular-touch": "github:angular/bower-angular-touch@1.4.4",
      "angular-ui-layout": "github:angular-ui/ui-layout@1.0.5",
      "angular-ui-select": "github:angular-ui/ui-select@0.12.1",
      "angular-ui-tree": "github:angular-ui-tree/angular-ui-tree@2.8.0",
      "bootstrap": "github:twbs/bootstrap@3.3.5",
      "bootstrap3-dialog": "github:nakupanda/bootstrap3-dialog@1.34.5",
      "css": "github:systemjs/plugin-css@0.1.13",
      "jmcriffey/bower-traceur": "github:jmcriffey/bower-traceur@0.0.91",
      "jmcriffey/bower-traceur-runtime": "github:jmcriffey/bower-traceur-runtime@0.0.91",
      "jquery": "github:components/jquery@2.1.4",
      "nakupanda/bootstrap3-dialog": "github:nakupanda/bootstrap3-dialog@1.34.5",
      "typescript": "npm:typescript@1.5.3"
    },
    "github:angular/bower-angular-animate@1.4.4": {
      "angular": "github:angular/bower-angular@1.4.4"
    },
    "github:angular/bower-angular-route@1.4.4": {
      "angular": "github:angular/bower-angular@1.4.4"
    },
    "github:angular/bower-angular-sanitize@1.4.4": {
      "angular": "github:angular/bower-angular@1.4.4"
    },
    "github:angular/bower-angular-touch@1.4.4": {
      "angular": "github:angular/bower-angular@1.4.4"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.4.3"
    },
    "github:jspm/nodelibs-os@0.1.0": {
      "os-browserify": "npm:os-browserify@0.1.2"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.1": {
      "process": "npm:process@0.10.1"
    },
    "github:mgcrea/angular-strap@2.3.1": {
      "angular": "github:angular/bower-angular@1.4.4"
    },
    "github:nakupanda/bootstrap3-dialog@1.34.5": {
      "bootstrap": "github:twbs/bootstrap@3.3.5"
    },
    "github:twbs/bootstrap@3.3.5": {
      "jquery": "github:components/jquery@2.1.4"
    },
    "npm:angular-schema-form-dynamic-select@0.11.6": {
      "angular-schema-form": "npm:angular-schema-form@0.8.7",
      "angular-strap": "npm:angular-strap@2.3.1",
      "bootstrap": "npm:bootstrap@3.3.5",
      "ui-select": "npm:ui-select@0.11.2"
    },
    "npm:angular-schema-form@0.8.7": {
      "angular": "npm:angular@1.4.4",
      "angular-sanitize": "npm:angular-sanitize@1.4.4",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "objectpath": "npm:objectpath@1.2.1",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "tv4": "npm:tv4@1.0.18"
    },
    "npm:angular-strap@2.3.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:angular@1.4.4": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:bootstrap@3.3.5": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:buffer@3.4.3": {
      "base64-js": "npm:base64-js@0.0.8",
      "ieee754": "npm:ieee754@1.1.6",
      "is-array": "npm:is-array@1.0.1"
    },
    "npm:os-browserify@0.1.2": {
      "os": "github:jspm/nodelibs-os@0.1.0"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:typescript@1.5.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "os": "github:jspm/nodelibs-os@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "readline": "github:jspm/nodelibs-readline@0.1.0"
    },
    "npm:typescript@1.6.0-dev.20150824": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "os": "github:jspm/nodelibs-os@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "readline": "github:jspm/nodelibs-readline@0.1.0"
    },
    "npm:ui-select@0.11.2": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    }
  }
});
```

**Comment by guybedford** [comment]
Your map value in:

```javascript
      "map": {
        "mbe-nodes": "github:OptimalBPM/mbe-nodes@0.4.10"
      }
```

Is overriding the base map here. I actually just fixed this in SystemJS 0.18.13, so it should work with a `jspm dl-loader --edge` here.

**Comment by nicklasb** [comment]
Hm, the problem is that now it has started to load nodes.js.ts, it seems to disregard the `defaultExtension: "js"`-setting.

**Comment by nicklasb** [comment]
Oops. Took a chance and did `jspm dl-loader --edge b7abc2` to see if it went back to the last version. That didn't work out well, now I am not getting back to the new version.  :-)

**Comment by guybedford** [comment]
It should be working now on edge.. Let me know!

**Comment by nicklasb** [comment]
Well, almost, now it loads: 
`http://localhost:63342/optimalbpm/optimalbpm/broker/ui/jspm_packages/github/OptimalBPM/mbe-nodes@0.4.10/index.ts` instead of .js.

**Comment by guybedford** [comment]
Great, that's actually correct if the `defaultExtension` is set to `ts`. Add a `map: { './index': './index.js' }` to make an exception.

**Comment by nicklasb** [comment]
Used: `jspm dl-loader --edge master` to seemingly get back, did I guess that right?

**Comment by nicklasb** [comment]
Does that mean I can use a TypeScript index.ts?

**Comment by guybedford** [comment]
Yes that's fine!

There's only one `jspm dl-loader --edge` which is master. `jspm dl-loader --latest` will load stable.

**Comment by nicklasb** [comment]
Good stuff, that will make the project almost pure .ts, only exception being jspm_config.js.

A comment on dl-loader:
I tried to get back to the commit b7abc2, and then it started acting strange, it continued to use that even if I used `jspm dl-loader --edge`.

**Comment by nicklasb** [comment]
Why is the parameter to --edge used as the transpiler? 
`jspm dl-loader --latest` sets the transpiler to "latest".

```js
System.config({
  defaultJSExtensions: true,
  transpiler: "latest",
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
```

**Comment by guybedford** [comment]
Make sure you're running the jspm 0.16 release.

**Comment by nicklasb** [comment]
I am running that version. 

Either way, if I then set it right manually, jspm let it be, and now everything works.

**Comment by guybedford** [comment]
Great to hear that, thanks for helping work through these boundary cases, closing for now but let me know if anything else pops up.

**Comment by nicklasb** [comment]
It is likely that TypeScript won't be a boundary case for that a long, so it is really great that SystemJS/JSPM handles a full-on .ts-solution like this one elegantly. 

You are doing some really awesome work with this framework, frankly, I don't see why anyone would want to use any other framework. The only drawback perhaps is that the registry is a git repo, which might be difficult hard to maintain when it grows. Other than that, it feels lite the NBT.

**Comment by guybedford** [comment]
Thanks! It helps you clarified you didn't mean nothing-but-trouble there :) Certainly the registry can always be generalized later, transparency is important for now though.

**Comment by nicklasb** [comment]
Yeah. Also, I felt that it was a little bit too wannabe-nerd to abbreviate that. 
Transparency is for the weak of faith. :-)

**Comment by nicklasb** [comment]
Hm. Using SystemJS v0.18.14 (or rather, --edge), same config as above, and is looking at a require in a non-typescript package.
There is a file in the angular-schema-form npm-package that does a `require('angular-schema-form')` that fails to resolve.
However, if I add 'angular-schema-form' to the top map level, it works. 

This has nothing to do with TypeScript, has there been a regression somewhere?

**Comment by nicklasb** [comment]
Hm.#2:
Now it started to work again...`jspm dl-loader --edge` seems to produce strange results under github ddos:es...
