### ISSUE TITLE
404ing on react dependencies?

### ISSUE THREAD

**Issue by staxmanade** [systemjs/systemjs#755]
Trying out a very basic React page using JSPM over on [plnkr.co](http://plnkr.co/edit/TfvRer4Ijvoub4xFj9VO?p=preview) I get a number of `404s` for the following url's.

https://npm.jspm.io/react-tools@0.13.3/vendor/inline-source-map
https://npm.jspm.io/react-tools@0.13.3/vendor/fbtransform/visitors
https://npm.jspm.io/jstransform@10.1.0/src/utils
https://npm.jspm.io/source-map@0.1.31/lib/source-map/source-map-generator
https://npm.jspm.io/source-map@0.1.31/lib/source-map/source-map-consumer
https://npm.jspm.io/source-map@0.1.31/lib/source-map/source-node

However if I manually add `.js` to the end of the above url's they look to return valid JS.

### Is there something I need to do to get these to correctly load the dependent resources above?

**[plnkr.co sample here](http://plnkr.co/edit/TfvRer4Ijvoub4xFj9VO?p=preview)**

Below is a copy/paste of the chrome console for the above plnkr.co.

```
GET https://npm.jspm.io/react-tools@0.13.3/vendor/inline-source-map 404 (Not Found)R @ system@0.18.17.src.js:1050o.fetch @ system@0.18.17.src.js:1084o.fetch @ system@0.18.17.src.js:1083g @ system@0.18.17.src.js:1667(anonymous function) @ system@0.18.17.src.js:2184n @ system@0.18.17.src.js:2427a @ system@0.18.17.src.js:3008n @ system@0.18.17.src.js:3681(anonymous function) @ system@0.18.17.src.js:3770(anonymous function) @ system@0.18.17.src.js:3991(anonymous function) @ system@0.18.17.src.js:326
system@0.18.17.src.js:1050 GET https://npm.jspm.io/react-tools@0.13.3/vendor/fbtransform/visitors 404 (Not Found)R @ system@0.18.17.src.js:1050o.fetch @ system@0.18.17.src.js:1084o.fetch @ system@0.18.17.src.js:1083g @ system@0.18.17.src.js:1667(anonymous function) @ system@0.18.17.src.js:2184n @ system@0.18.17.src.js:2427a @ system@0.18.17.src.js:3008n @ system@0.18.17.src.js:3681(anonymous function) @ system@0.18.17.src.js:3770(anonymous function) @ system@0.18.17.src.js:3991(anonymous function) @ system@0.18.17.src.js:326
run.plnkr.co/:1 Uncaught (in promise) Error: XHR error (404 Not Found) loading https://npm.jspm.io/react-tools@0.13.3/vendor/inline-source-map
	Error loading https://npm.jspm.io/react-tools@0.13.3/vendor/inline-source-map as "./vendor/inline-source-map" from https://npm.jspm.io/react-tools@0.13.3/main.js
	Error loading https://registry.jspm.io/js/app.jsx.js!https://registry.jspm.io/jsx.js
    at r (https://jspm.io/system@0.18.17.js:5:11565)
    at XMLHttpRequest.o.onreadystatechange (https://jspm.io/system@0.18.17.js:5:12090)t @ system@0.18.17.src.js:43g @ system@0.18.17.src.js:635(anonymous function) @ system@0.18.17.src.js:440
system@0.18.17.src.js:1050 GET https://npm.jspm.io/jstransform@10.1.0/src/utils 404 (Not Found)R @ system@0.18.17.src.js:1050o.fetch @ system@0.18.17.src.js:1084o.fetch @ system@0.18.17.src.js:1083g @ system@0.18.17.src.js:1667(anonymous function) @ system@0.18.17.src.js:2184n @ system@0.18.17.src.js:2427a @ system@0.18.17.src.js:3008n @ system@0.18.17.src.js:3681(anonymous function) @ system@0.18.17.src.js:3770(anonymous function) @ system@0.18.17.src.js:3991(anonymous function) @ system@0.18.17.src.js:326
system@0.18.17.src.js:1050 GET https://npm.jspm.io/source-map@0.1.31/lib/source-map/source-map-generator 404 (Not Found)R @ system@0.18.17.src.js:1050o.fetch @ system@0.18.17.src.js:1084o.fetch @ system@0.18.17.src.js:1083g @ system@0.18.17.src.js:1667(anonymous function) @ system@0.18.17.src.js:2184n @ system@0.18.17.src.js:2427a @ system@0.18.17.src.js:3008n @ system@0.18.17.src.js:3681(anonymous function) @ system@0.18.17.src.js:3770(anonymous function) @ system@0.18.17.src.js:3991(anonymous function) @ system@0.18.17.src.js:326
system@0.18.17.src.js:1050 GET https://npm.jspm.io/source-map@0.1.31/lib/source-map/source-map-consumer 404 (Not Found)R @ system@0.18.17.src.js:1050o.fetch @ system@0.18.17.src.js:1084o.fetch @ system@0.18.17.src.js:1083g @ system@0.18.17.src.js:1667(anonymous function) @ system@0.18.17.src.js:2184n @ system@0.18.17.src.js:2427a @ system@0.18.17.src.js:3008n @ system@0.18.17.src.js:3681(anonymous function) @ system@0.18.17.src.js:3770(anonymous function) @ system@0.18.17.src.js:3991(anonymous function) @ system@0.18.17.src.js:326
system@0.18.17.src.js:1050 GET https://npm.jspm.io/source-map@0.1.31/lib/source-map/source-node 404 (Not Found)

```

> also sorry if this is not the correct place to report this - just let me know if there is a better place to post this info.

**Comment by guybedford** [comment]
This was fixed recently actually to ensure `defaultJSExtensions` is enabled for jspm's SystemJS build. Try clearing your browser cache and loading it again?

**Comment by staxmanade** [comment]
Thanks for the idea... I cleared my browser cache which got me past the above errors.

I then got this error:

```
Uncaught (in promise) Error: XHR error (404 Not Found) loading https://registry.jspm.io/amdefine.js
	Error loading https://registry.jspm.io/amdefine.js as "amdefine" from https://npm.jspm.io/source-map@0.1.31/lib/source-map/source-map-generator.js
	Error loading https://registry.jspm.io/js/app.jsx!https://registry.jspm.io/jsx.js
    at r (https://jspm.io/system@0.18.17.js:5:11565)
    at XMLHttpRequest.o.onreadystatechange (https://jspm.io/system@0.18.17.js:5:12090)
```

I updated my `config.js` to use this:

```
System.config({
  map:{
    "amdefine": "npm:amdefine@1.0.0"
  }
});
```

and that appeared to work for `amdefine`.

### However, now I'm stuck on this one... ` Module github:jspm/nodelibs-buffer@0.1 not declared as a dependency.` 

```
Uncaught TypeError: Module github:jspm/nodelibs-buffer@0.1 not declared as a dependency.(anonymous function) @ system@0.18.17.src.js:2099(anonymous function) @ inline-source-map.src.js:17(anonymous function) @ inline-source-map.src.js:17D @ system@0.18.17.src.js:1241s.metadata.execute @ system@0.18.17.src.js:2720u @ system@0.18.17.src.js:2093i @ system@0.18.17.src.js:2061(anonymous function) @ system@0.18.17.src.js:2097(anonymous function) @ main.src.js:8(anonymous function) @ main.src.js:31(anonymous function) @ main.src.js:65D @ system@0.18.17.src.js:1241s.metadata.execute @ system@0.18.17.src.js:2720u @ system@0.18.17.src.js:2093i @ system@0.18.17.src.js:2061(anonymous function) @ system@0.18.17.src.js:2097(anonymous function) @ react-tools@0.13.js:1(anonymous function) @ react-tools@0.13.js:2D @ system@0.18.17.src.js:1241s.metadata.execute @ system@0.18.17.src.js:2720u @ system@0.18.17.src.js:2093i @ system@0.18.17.src.js:2061(anonymous function) @ system@0.18.17.src.js:2097(anonymous function) @ jsx.src.js:5(anonymous function) @ jsx.src.js:10D @ system@0.18.17.src.js:1241s.metadata.execute @ system@0.18.17.src.js:2720u @ system@0.18.17.src.js:2093i @ system@0.18.17.src.js:2061(anonymous function) @ system@0.18.17.src.js:2097(anonymous function) @ jsx.js:1(anonymous function) @ jsx.js:2D @ system@0.18.17.src.js:1241s.metadata.execute @ system@0.18.17.src.js:2720u @ system@0.18.17.src.js:2093a @ system@0.18.17.src.js:1936Promise.all.then.execute @ system@0.18.17.src.js:2288b @ system@0.18.17.src.js:715x @ system@0.18.17.src.js:916p @ system@0.18.17.src.js:569h @ system@0.18.17.src.js:617(anonymous function) @ system@0.18.17.src.js:430
system@0.18.17.src.js:1246 Uncaught Script error.
	Evaluating https://npm.jspm.io/react-tools@0.13.3/vendor/inline-source-map.jsD @ system@0.18.17.src.js:1246s.metadata.execute @ system@0.18.17.src.js:2720u @ system@0.18.17.src.js:2093i @ system@0.18.17.src.js:2061(anonymous function) @ system@0.18.17.src.js:2097(anonymous function) @ main.src.js:8(anonymous function) @ main.src.js:31(anonymous function) @ main.src.js:65D @ system@0.18.17.src.js:1241s.metadata.execute @ system@0.18.17.src.js:2720u @ system@0.18.17.src.js:2093i @ system@0.18.17.src.js:2061(anonymous function) @ system@0.18.17.src.js:2097(anonymous function) @ react-tools@0.13.js:1(anonymous function) @ react-tools@0.13.js:2D @ system@0.18.17.src.js:1241s.metadata.execute @ system@0.18.17.src.js:2720u @ system@0.18.17.src.js:2093i @ system@0.18.17.src.js:2061(anonymous function) @ system@0.18.17.src.js:2097(anonymous function) @ jsx.src.js:5(anonymous function) @ jsx.src.js:10D @ system@0.18.17.src.js:1241s.metadata.execute @ system@0.18.17.src.js:2720u @ system@0.18.17.src.js:2093i @ system@0.18.17.src.js:2061(anonymous function) @ system@0.18.17.src.js:2097(anonymous function) @ jsx.js:1(anonymous function) @ jsx.js:2D @ system@0.18.17.src.js:1241s.metadata.execute @ system@0.18.17.src.js:2720u @ system@0.18.17.src.js:2093a @ system@0.18.17.src.js:1936Promise.all.then.execute @ system@0.18.17.src.js:2288b @ system@0.18.17.src.js:715x @ system@0.18.17.src.js:916p @ system@0.18.17.src.js:569h @ system@0.18.17.src.js:617(anonymous function) @ system@0.18.17.src.js:430
system@0.18.17.src.js:1246 Uncaught Script error.
	Evaluating https://npm.jspm.io/react-tools@0.13.3/main.jsD @ system@0.18.17.src.js:1246s.metadata.execute @ system@0.18.17.src.js:2720u @ system@0.18.17.src.js:2093i @ system@0.18.17.src.js:2061(anonymous function) @ system@0.18.17.src.js:2097(anonymous function) @ react-tools@0.13.js:1(anonymous function) @ react-tools@0.13.js:2D @ system@0.18.17.src.js:1241s.metadata.execute @ system@0.18.17.src.js:2720u @ system@0.18.17.src.js:2093i @ system@0.18.17.src.js:2061(anonymous function) @ system@0.18.17.src.js:2097(anonymous function) @ jsx.src.js:5(anonymous function) @ jsx.src.js:10D @ system@0.18.17.src.js:1241s.metadata.execute @ system@0.18.17.src.js:2720u @ system@0.18.17.src.js:2093i @ system@0.18.17.src.js:2061(anonymous function) @ system@0.18.17.src.js:2097(anonymous function) @ jsx.js:1(anonymous function) @ jsx.js:2D @ system@0.18.17.src.js:1241s.metadata.execute @ system@0.18.17.src.js:2720u @ system@0.18.17.src.js:2093a @ system@0.18.17.src.js:1936Promise.all.then.execute @ system@0.18.17.src.js:2288b @ system@0.18.17.src.js:715x @ system@0.18.17.src.js:916p @ system@0.18.17.src.js:569h @ system@0.18.17.src.js:617(anonymous function) @ system@0.18.17.src.js:430
system@0.18.17.src.js:1246 Uncaught Script error.
	Evaluating https://npm.jspm.io/react-tools@0.13.jsD @ system@0.18.17.src.js:1246s.metadata.execute @ system@0.18.17.src.js:2720u @ system@0.18.17.src.js:2093i @ system@0.18.17.src.js:2061(anonymous function) @ system@0.18.17.src.js:2097(anonymous function) @ jsx.src.js:5(anonymous function) @ jsx.src.js:10D @ system@0.18.17.src.js:1241s.metadata.execute @ system@0.18.17.src.js:2720u @ system@0.18.17.src.js:2093i @ system@0.18.17.src.js:2061(anonymous function) @ system@0.18.17.src.js:2097(anonymous function) @ jsx.js:1(anonymous function) @ jsx.js:2D @ system@0.18.17.src.js:1241s.metadata.execute @ system@0.18.17.src.js:2720u @ system@0.18.17.src.js:2093a @ system@0.18.17.src.js:1936Promise.all.then.execute @ system@0.18.17.src.js:2288b @ system@0.18.17.src.js:715x @ system@0.18.17.src.js:916p @ system@0.18.17.src.js:569h @ system@0.18.17.src.js:617(anonymous function) @ system@0.18.17.src.js:430
system@0.18.17.src.js:1246 Uncaught Script error.
	Evaluating https://github.jspm.io/floatdrop/plugin-jsx@1.1.0/jsx.jsD @ system@0.18.17.src.js:1246s.metadata.execute @ system@0.18.17.src.js:2720u @ system@0.18.17.src.js:2093i @ system@0.18.17.src.js:2061(anonymous function) @ system@0.18.17.src.js:2097(anonymous function) @ jsx.js:1(anonymous function) @ jsx.js:2D @ system@0.18.17.src.js:1241s.metadata.execute @ system@0.18.17.src.js:2720u @ system@0.18.17.src.js:2093a @ system@0.18.17.src.js:1936Promise.all.then.execute @ system@0.18.17.src.js:2288b @ system@0.18.17.src.js:715x @ system@0.18.17.src.js:916p @ system@0.18.17.src.js:569h @ system@0.18.17.src.js:617(anonymous function) @ system@0.18.17.src.js:430
run.plnkr.co/:1 Uncaught (in promise) Script error.
	Evaluating https://registry.jspm.io/jsx.js
	Error loading https://registry.jspm.io/jsx.js
	Error loading https://registry.jspm.io/js/app.jsx!https://registry.jspm.io/jsx.js
```

I tried installing it locally with `jspm` to see what it would put inside the `config.js` but copying/pasting the `map` to my config doesn't seem to resolve the above error. 

Any thoughts?

**Comment by guybedford** [comment]
Yes, the jsx plugin seems to be fairly broken. Unfortunately I can't write all jspm plugins myself. I've got this working for you in http://plnkr.co/edit/YopXBIOHwEkpP2TL4pBl?p=preview.

**Comment by staxmanade** [comment]
O_o - that's awesome you got it working. What's the magic that made this work? Is it because you specify babel transpiler and somehow babel is doing the jsx work instead?

Thanks for this...

**Comment by guybedford** [comment]
Yes exactly, Babel comes with JSX support. The plugin option should be working though here, so your attempt was completely valid.
