### ISSUE TITLE
Resolve a module path without requiring it

### ISSUE THREAD

**Issue by bottleofwater** [systemjs/systemjs#807]
Hi,

The following code used to work (0.16.6):

```js
let System = require('systemjs');
console.log(System.version);

System.paths['this/*'] = 'file:///tmp/*.js';

async function resolveName(name) {
    return await System.locate({ name });
}

resolveName('this/folder/file').then(path => {
    console.log(path); // should be "file:///tmp/folder/file.js"
}).catch(error => {
    console.log(error.stack);
});
```

However, since I upgraded to the 0.19.2, it doesn't work anymore (it throw if I don't add an empty metadata property in the locate call, and return the module name instead of its resolved path once I add the empty metadata) - how can I achieve the same effect?

**Comment by guybedford** [comment]
Are you sure? The above works fine for me.

**Comment by bottleofwater** [comment]
Yep, sure. I've just runned the exact test case with babel-node and a fresh new systemjs install on iojs, and I ran into the following:

```
TypeError: Cannot read property 'loader' of undefined
    at /tmp/node_modules/systemjs/dist/system.src.js:3931:35
    at run (/home/arcanis/.nvm/versions/io.js/v3.3.0/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:89:39)
    at /home/arcanis/.nvm/versions/io.js/v3.3.0/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/home/arcanis/.nvm/versions/io.js/v3.3.0/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/$.microtask.js:17:13)
    at doNTCallback0 (node.js:407:9)
    at process._tickDomainCallback (node.js:377:13)
    at Function.Module.runMain (module.js:473:11)
    at Object.<anonymous> (/home/arcanis/.nvm/versions/io.js/v3.3.0/lib/node_modules/babel/lib/_babel-node.js:144:25)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
```

Which makes sense, since the line 3931 is the following:

```
var plugin = load.metadata.loader;
```

So it should crash without a metadata property.

**Comment by guybedford** [comment]
Yes, when calling locate manually you need to add an empty metadata object to match the expected signature like:

```javascript
System.locate({ name, metadata: {} });
```

**Comment by bottleofwater** [comment]
Yep, but even if I do this, I get `"this/folder/file"`, not the expected `"file:///tmp/folder/file.js"`.

**Comment by guybedford** [comment]
Right, use `System.normalize`.

**Comment by bottleofwater** [comment]
I see, thanks for your quick answer. The following code works fine:

```
let System = require('systemjs');
console.log(System.version);

System.paths['this/*'] = 'file:///tmp/*.js';

async function resolveName(name) {
    return await System.normalize(name);
}

resolveName('this/folder/file').then(path => {
    console.log(path); // should be "file:///tmp/folder/file.js"
}).catch(error => {
    console.log(error.stack);
});
```
