### ISSUE TITLE
Invalid URL is thrown when requiring systemjs in jest test cases

### ISSUE THREAD

**Issue by pawelgalazka** [systemjs/systemjs#840]
I'm not sure where the problem lies if it's jest (https://github.com/facebook/jest/issues/547) or system js, but either way:

app.spec.js:
```javascript
jest.autoMockOff();
var System = require('systemjs');
```
```
jest
```

code above throws: 
```
● Runtime Error
TypeError: /Users/pawelgalazka/Projects/firestart-seed/spec/app.spec.js: 
/Users/pawelgalazka/Projects/firestart-seed/node_modules/systemjs/index.js: 
/Users/pawelgalazka/Projects/firestart-seed/node_modules/systemjs/dist/system.src.js: 
Invalid URL
```

requiring system js works fine if I do it in a pure node script:

test.js:
```
var System = require('systemjs');
```
```
node test.js
```

Configuration in package.json:

```
  "jest": {
    "testFileExtensions": [
      "js"
    ],
    "moduleFileExtensions": [
      "js",
      "json",
      "jsx"
    ],
    "testDirectoryName": "spec",
    "testPathDirs": [
      "spec"
    ],
    "unmockedModulePathPatterns": [
      "./node_modules/systemjs/"
    ],
    "verbose": true
  },
```

**Comment by guybedford** [comment]
Any idea what line it's giving that error on here?

**Comment by pawelgalazka** [comment]
jest is not throwing any stacktrace, although I was able to print it from the place where the exception is throwing. By the way, my systemjs version: 0.19.4. Looks like jsdom is messing around.

```
RLStateMachine.parseNoScheme [as parse3] (/Users/pawelgalazka/Projects/firestart-seed/node_modules/jest-cli/node_modules/jsdom/node_modules/whatwg-url-compat/lib/url.js:564:26)
  at new URLStateMachine (/Users/pawelgalazka/Projects/firestart-seed/node_modules/jest-cli/node_modules/jsdom/node_modules/whatwg-url-compat/lib/url.js:497:35)
  at URL.init (/Users/pawelgalazka/Projects/firestart-seed/node_modules/jest-cli/node_modules/jsdom/node_modules/whatwg-url-compat/lib/url.js:1329:21)
  at new URL (/Users/pawelgalazka/Projects/firestart-seed/node_modules/jest-cli/node_modules/jsdom/node_modules/whatwg-url-compat/lib/url.js:1345:10)
  at /Users/pawelgalazka/Projects/firestart-seed/node_modules/systemjs/dist/system.src.js:1485:18
  at bootstrap (/Users/pawelgalazka/Projects/firestart-seed/node_modules/systemjs/dist/system.src.js:4525:3)
  at /Users/pawelgalazka/Projects/firestart-seed/node_modules/systemjs/dist/system.src.js:4563:3
  at Object.<anonymous> (/Users/pawelgalazka/Projects/firestart-seed/node_modules/systemjs/dist/system.src.js:4567:3)
  at Object.runContentWithLocalBindings (/Users/pawelgalazka/Projects/firestart-seed/node_modules/jest-cli/src/lib/utils.js:527:17)
  at Loader._execModule (/Users/pawelgalazka/Projects/firestart-seed/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:239:9)
  at Loader.requireModule (/Users/pawelgalazka/Projects/firestart-seed/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:902:12)
  at Loader.requireModuleOrMock (/Users/pawelgalazka/Projects/firestart-seed/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:923:17)
  at Object.<anonymous> (/Users/pawelgalazka/Projects/firestart-seed/node_modules/systemjs/index.js:26:22)
  at Object.runContentWithLocalBindings (/Users/pawelgalazka/Projects/firestart-seed/node_modules/jest-cli/src/lib/utils.js:527:17)
  at Loader._execModule (/Users/pawelgalazka/Projects/firestart-seed/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:239:9)
  at Loader.requireModule (/Users/pawelgalazka/Projects/firestart-seed/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:902:12)
  at Loader.requireModuleOrMock (/Users/pawelgalazka/Projects/firestart-seed/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:923:17)
  at Object.<anonymous> (/Users/pawelgalazka/Projects/firestart-seed/spec/app.spec.js:3:14)
  at Object.runContentWithLocalBindings (/Users/pawelgalazka/Projects/firestart-seed/node_modules/jest-cli/src/lib/utils.js:527:17)
  at Loader._execModule (/Users/pawelgalazka/Projects/firestart-seed/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:239:9)
  at Loader.requireModule (/Users/pawelgalazka/Projects/firestart-seed/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:902:12)
  at jasmineTestRunner (/Users/pawelgalazka/Projects/firestart-seed/node_modules/jest-cli/src/jasmineTestRunner/jasmineTestRunner.js:284:16)
  at /Users/pawelgalazka/Projects/firestart-seed/node_modules/jest-cli/src/TestRunner.js:379:12
  at process._tickCallback (node.js:356:9)
```

**Comment by pawelgalazka** [comment]
It looks like there is a problem with baseURI detection in systemjs when it is used in jsdom. `system.src.js:148: var baseURIObj = new URL(baseURI);`, baseURI is an empty string. On system.src.js:81 baseURI is 'about:blank', after processing (line 82) it becomes the empty string.

**Comment by guybedford** [comment]
Thanks, that makes sense. This is caused by https://github.com/ModuleLoader/es6-module-loader/blob/master/src/wrapper-start.js#L78. Perhaps we should just switch to the second conditional branch there for jsDOM support.

**Comment by dmatteo** [comment]
@guybedford can't this be fixed using the same *check* as https://github.com/systemjs/systemjs/issues/821?

**Comment by guybedford** [comment]
@dmatteo yes certainly. @pawelgalazka can you confirm `process.cwd()` would be the reference to the location of the HTML page itself, or is that something else in jsdom?

**Comment by pawelgalazka** [comment]
@guybedford yes it's fine, I've created a pull request for that

**Comment by guybedford** [comment]
@pawelgalazka I just did a quick test and it appears that both `process` and `require` are not by default available in jsdom environments.

In the test page where the `baseURI` is set to `about:blank`, there isn't actually a correct value to use for `baseURL` since `about:blank` is an invalid URL to begin with. That is, I think the behaviour is actually completely correct currently.

I would suggest ensuring you manipulate the jsdom instance to have a valid location / baseURI by setting the `referrer` config in jsdom.

**Comment by guybedford** [comment]
@pawelgalazka let me know if the suggestion above makes sense and works out for you here. Look forward to hearing further how things get on with the work there.
