### ISSUE TITLE
'Map' is undefined error when loading system-polyfills.js in IE10

### ISSUE THREAD

**Issue by mikeyoon** [systemjs/systemjs#962]
In IE10 (via the Win7/IE10 VBox VM provided by MS), I get the following exception when loading in system-polyfills.js:

Potentially unhandled rejection [3] ReferenceError: 'Map' is undefined
   at CompilerHost (Unknown script code:18:9)
   at createServices (Unknown script code:67:5)
   at Anonymous function (Unknown script code:16:9)
   at M (http://assets.modeanalytics.dev:3001/jspm_packages/system-polyfills.js:4:8723)
   at H (http://assets.modeanalytics.dev:3001/jspm_packages/system-polyfills.js:4:8310)
   at when (http://assets.modeanalytics.dev:3001/jspm_packages/system-polyfills.js:4:12042)
   at run (http://assets.modeanalytics.dev:3001/jspm_packages/system-polyfills.js:4:11076)
   at _drain (http://assets.modeanalytics.dev:3001/jspm_packages/system-polyfills.js:4:3014)
   at drain (http://assets.modeanalytics.dev:3001/jspm_packages/system-polyfills.js:4:2681) 

This is with SystemJS v0.19.6.

**Comment by guybedford** [comment]
It sounds like this issue is in your own code that uses `Map` as opposed to the system-polyfills.js file (which is just the part of the Promise polyfill that finally handles the error). The first three lines are the ones to check here.

If this is in ES6 code that is using Babel, do let me know though how it is happening if you still can't find the reason.

**Comment by mikeyoon** [comment]
Makes sense. I'm using typescript as ES6 transpiler via plugin-typescript and CompilerHost is a TS thing. I'll post this over there then. Thanks!
